/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_Message operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { MessageListItem } from "@/openapi/litestarAPI.schemas";
import { MessageDirection, MessageState } from "@/openapi/litestarAPI.schemas";

export const messageColumnDefs = createColumnBuilder<MessageListItem>()
  .enum("direction", { header: "Direction", filterable: true, options: Object.values(MessageDirection) })
  .status("state", { header: "State", filterable: true, options: Object.values(MessageState) })
  .text("subject", { header: "Subject" })
  .text("from_email", { header: "From Email" })
  .text("snippet", { header: "Snippet" })
  .datetime("received_at", { header: "Received", sortable: true, hideOnMobile: true })
  .datetime("sent_at", { header: "Sent", sortable: true, hideOnMobile: true })
  .datetime("read_at", { header: "Read", filterable: true, hideOnMobile: true })
  .datetime("archived_at", { header: "Archived", filterable: true, hideOnMobile: true })
  .build();

export const MessageSortableColumn = {
  created_at: 'created_at',
  received_at: 'received_at',
  sent_at: 'sent_at',
} as const;

export const MessageFilterableColumn = {
  archived_at: 'archived_at',
  direction: 'direction',
  email_thread_id: 'email_thread_id',
  read_at: 'read_at',
  state: 'state',
} as const;
