/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_SurveyMedia operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { SurveyMediaListItem } from "@/openapi/litestarAPI.schemas";


export const surveyMediaColumnDefs = createColumnBuilder<SurveyMediaListItem>()
  .text("caption", { header: "Caption" })
  .number("sort_order", { header: "Sort Order", sortable: true })
  .text("file_name", { header: "File Name" })
  .text("file_type", { header: "File Type" })
  .text("mime_type", { header: "Mime Type" })
  .text("view_url", { header: "View Url" })
  .text("thumbnail_url", { header: "Thumbnail Url" })
  .build();

export const SurveyMediaSortableColumn = {
  created_at: 'created_at',
  sort_order: 'sort_order',
} as const;

export const SurveyMediaFilterableColumn = {
  node_id: 'node_id',
  survey_id: 'survey_id',
} as const;
