/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ListRequest,
  ListSurveyMedia400,
  PagedResponseAppDomainSurveysSchemasSurveyMediaListItem,
  SurveyMediaDetail,
  SurveyMediaIdDetailHandler400
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary DetailHandler
 */
export const surveyMediaIdDetailHandler = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SurveyMediaDetail>(
      {url: `/survey-media/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getSurveyMediaIdDetailHandlerQueryKey = (id?: string,) => {
    return [
    `/survey-media/${id}`
    ] as const;
    }

    
export const getSurveyMediaIdDetailHandlerQueryOptions = <TData = Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError = SurveyMediaIdDetailHandler400>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSurveyMediaIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>> = ({ signal }) => surveyMediaIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SurveyMediaIdDetailHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>>
export type SurveyMediaIdDetailHandlerQueryError = SurveyMediaIdDetailHandler400


export function useSurveyMediaIdDetailHandler<TData = Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError = SurveyMediaIdDetailHandler400>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSurveyMediaIdDetailHandler<TData = Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError = SurveyMediaIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSurveyMediaIdDetailHandler<TData = Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError = SurveyMediaIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useSurveyMediaIdDetailHandler<TData = Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError = SurveyMediaIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSurveyMediaIdDetailHandlerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getSurveyMediaIdDetailHandlerSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError = SurveyMediaIdDetailHandler400>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSurveyMediaIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>> = ({ signal }) => surveyMediaIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SurveyMediaIdDetailHandlerSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>>
export type SurveyMediaIdDetailHandlerSuspenseQueryError = SurveyMediaIdDetailHandler400


export function useSurveyMediaIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError = SurveyMediaIdDetailHandler400>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSurveyMediaIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError = SurveyMediaIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSurveyMediaIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError = SurveyMediaIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useSurveyMediaIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError = SurveyMediaIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyMediaIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSurveyMediaIdDetailHandlerSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ListHandler
 */
export const listSurveyMedia = (
    listRequest: ListRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PagedResponseAppDomainSurveysSchemasSurveyMediaListItem>(
      {url: `/survey-media`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listRequest, signal
    },
      );
    }
  



export const getListSurveyMediaQueryKey = (listRequest?: ListRequest,) => {
    return [
    `/survey-media`, listRequest
    ] as const;
    }

    
export const getListSurveyMediaQueryOptions = <TData = Awaited<ReturnType<typeof listSurveyMedia>>, TError = ListSurveyMedia400>(listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSurveyMediaQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSurveyMedia>>> = ({ signal }) => listSurveyMedia(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSurveyMediaQueryResult = NonNullable<Awaited<ReturnType<typeof listSurveyMedia>>>
export type ListSurveyMediaQueryError = ListSurveyMedia400


export function useListSurveyMedia<TData = Awaited<ReturnType<typeof listSurveyMedia>>, TError = ListSurveyMedia400>(
 listRequest: ListRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSurveyMedia>>,
          TError,
          Awaited<ReturnType<typeof listSurveyMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSurveyMedia<TData = Awaited<ReturnType<typeof listSurveyMedia>>, TError = ListSurveyMedia400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSurveyMedia>>,
          TError,
          Awaited<ReturnType<typeof listSurveyMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSurveyMedia<TData = Awaited<ReturnType<typeof listSurveyMedia>>, TError = ListSurveyMedia400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListSurveyMedia<TData = Awaited<ReturnType<typeof listSurveyMedia>>, TError = ListSurveyMedia400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSurveyMediaQueryOptions(listRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getListSurveyMediaSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listSurveyMedia>>, TError = ListSurveyMedia400>(listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSurveyMediaQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSurveyMedia>>> = ({ signal }) => listSurveyMedia(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSurveyMediaSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listSurveyMedia>>>
export type ListSurveyMediaSuspenseQueryError = ListSurveyMedia400


export function useListSurveyMediaSuspense<TData = Awaited<ReturnType<typeof listSurveyMedia>>, TError = ListSurveyMedia400>(
 listRequest: ListRequest, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSurveyMediaSuspense<TData = Awaited<ReturnType<typeof listSurveyMedia>>, TError = ListSurveyMedia400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSurveyMediaSuspense<TData = Awaited<ReturnType<typeof listSurveyMedia>>, TError = ListSurveyMedia400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListSurveyMediaSuspense<TData = Awaited<ReturnType<typeof listSurveyMedia>>, TError = ListSurveyMedia400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyMedia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSurveyMediaSuspenseQueryOptions(listRequest,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




