/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_User operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { UserListItem } from "@/openapi/litestarAPI.schemas";


export const userColumnDefs = createColumnBuilder<UserListItem>()
  .text("name", { header: "Name" })
  .text("email", { header: "Email" })
  .build();
