/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  CheckInboxLocalPartAvailable400,
  CheckInboxLocalPartAvailableParams,
  InboxAvailabilityResponse,
  ListRequest,
  ListUser400,
  PagedResponseAppDomainUsersRoutesUserListItem
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary ListHandler
 */
export const listUser = (
    listRequest: ListRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PagedResponseAppDomainUsersRoutesUserListItem>(
      {url: `/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listRequest, signal
    },
      );
    }
  



export const getListUserQueryKey = (listRequest?: ListRequest,) => {
    return [
    `/users`, listRequest
    ] as const;
    }

    
export const getListUserQueryOptions = <TData = Awaited<ReturnType<typeof listUser>>, TError = ListUser400>(listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUserQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUser>>> = ({ signal }) => listUser(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUserQueryResult = NonNullable<Awaited<ReturnType<typeof listUser>>>
export type ListUserQueryError = ListUser400


export function useListUser<TData = Awaited<ReturnType<typeof listUser>>, TError = ListUser400>(
 listRequest: ListRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUser>>,
          TError,
          Awaited<ReturnType<typeof listUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUser<TData = Awaited<ReturnType<typeof listUser>>, TError = ListUser400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUser>>,
          TError,
          Awaited<ReturnType<typeof listUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUser<TData = Awaited<ReturnType<typeof listUser>>, TError = ListUser400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListUser<TData = Awaited<ReturnType<typeof listUser>>, TError = ListUser400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUserQueryOptions(listRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getListUserSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listUser>>, TError = ListUser400>(listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUserQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUser>>> = ({ signal }) => listUser(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUserSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listUser>>>
export type ListUserSuspenseQueryError = ListUser400


export function useListUserSuspense<TData = Awaited<ReturnType<typeof listUser>>, TError = ListUser400>(
 listRequest: ListRequest, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUserSuspense<TData = Awaited<ReturnType<typeof listUser>>, TError = ListUser400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUserSuspense<TData = Awaited<ReturnType<typeof listUser>>, TError = ListUser400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListUserSuspense<TData = Awaited<ReturnType<typeof listUser>>, TError = ListUser400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listUser>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUserSuspenseQueryOptions(listRequest,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary CheckInboxAvailableHandler
 */
export const checkInboxLocalPartAvailable = (
    params: CheckInboxLocalPartAvailableParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<InboxAvailabilityResponse>(
      {url: `/users/inbox/available`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getCheckInboxLocalPartAvailableQueryKey = (params?: CheckInboxLocalPartAvailableParams,) => {
    return [
    `/users/inbox/available`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCheckInboxLocalPartAvailableQueryOptions = <TData = Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError = CheckInboxLocalPartAvailable400>(params: CheckInboxLocalPartAvailableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckInboxLocalPartAvailableQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>> = ({ signal }) => checkInboxLocalPartAvailable(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckInboxLocalPartAvailableQueryResult = NonNullable<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>>
export type CheckInboxLocalPartAvailableQueryError = CheckInboxLocalPartAvailable400


export function useCheckInboxLocalPartAvailable<TData = Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError = CheckInboxLocalPartAvailable400>(
 params: CheckInboxLocalPartAvailableParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>,
          TError,
          Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckInboxLocalPartAvailable<TData = Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError = CheckInboxLocalPartAvailable400>(
 params: CheckInboxLocalPartAvailableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>,
          TError,
          Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckInboxLocalPartAvailable<TData = Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError = CheckInboxLocalPartAvailable400>(
 params: CheckInboxLocalPartAvailableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary CheckInboxAvailableHandler
 */

export function useCheckInboxLocalPartAvailable<TData = Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError = CheckInboxLocalPartAvailable400>(
 params: CheckInboxLocalPartAvailableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCheckInboxLocalPartAvailableQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getCheckInboxLocalPartAvailableSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError = CheckInboxLocalPartAvailable400>(params: CheckInboxLocalPartAvailableParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckInboxLocalPartAvailableQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>> = ({ signal }) => checkInboxLocalPartAvailable(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckInboxLocalPartAvailableSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>>
export type CheckInboxLocalPartAvailableSuspenseQueryError = CheckInboxLocalPartAvailable400


export function useCheckInboxLocalPartAvailableSuspense<TData = Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError = CheckInboxLocalPartAvailable400>(
 params: CheckInboxLocalPartAvailableParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckInboxLocalPartAvailableSuspense<TData = Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError = CheckInboxLocalPartAvailable400>(
 params: CheckInboxLocalPartAvailableParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckInboxLocalPartAvailableSuspense<TData = Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError = CheckInboxLocalPartAvailable400>(
 params: CheckInboxLocalPartAvailableParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary CheckInboxAvailableHandler
 */

export function useCheckInboxLocalPartAvailableSuspense<TData = Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError = CheckInboxLocalPartAvailable400>(
 params: CheckInboxLocalPartAvailableParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof checkInboxLocalPartAvailable>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCheckInboxLocalPartAvailableSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




