/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_SurveyTemplate operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { SurveyTemplateListItem } from "@/openapi/litestarAPI.schemas";


export const surveyTemplateColumnDefs = createColumnBuilder<SurveyTemplateListItem>()
  .text("name", { header: "Name", sortable: true, filterable: true })
  .text("tags", { header: "Tags" })
  .build();

export const SurveyTemplateSortableColumn = {
  created_at: 'created_at',
  name: 'name',
} as const;

export const SurveyTemplateFilterableColumn = {
  created_at: 'created_at',
  name: 'name',
} as const;
