/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ListRequest,
  ListSurveyTemplate400,
  PagedResponseAppDomainSurveysSchemasSurveyTemplateListItem,
  SurveyTemplateDetail,
  SurveyTemplatesIdDetailHandler400
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary DetailHandler
 */
export const surveyTemplatesIdDetailHandler = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SurveyTemplateDetail>(
      {url: `/survey-templates/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getSurveyTemplatesIdDetailHandlerQueryKey = (id?: string,) => {
    return [
    `/survey-templates/${id}`
    ] as const;
    }

    
export const getSurveyTemplatesIdDetailHandlerQueryOptions = <TData = Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError = SurveyTemplatesIdDetailHandler400>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSurveyTemplatesIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>> = ({ signal }) => surveyTemplatesIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SurveyTemplatesIdDetailHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>>
export type SurveyTemplatesIdDetailHandlerQueryError = SurveyTemplatesIdDetailHandler400


export function useSurveyTemplatesIdDetailHandler<TData = Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError = SurveyTemplatesIdDetailHandler400>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSurveyTemplatesIdDetailHandler<TData = Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError = SurveyTemplatesIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSurveyTemplatesIdDetailHandler<TData = Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError = SurveyTemplatesIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useSurveyTemplatesIdDetailHandler<TData = Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError = SurveyTemplatesIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSurveyTemplatesIdDetailHandlerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getSurveyTemplatesIdDetailHandlerSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError = SurveyTemplatesIdDetailHandler400>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSurveyTemplatesIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>> = ({ signal }) => surveyTemplatesIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SurveyTemplatesIdDetailHandlerSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>>
export type SurveyTemplatesIdDetailHandlerSuspenseQueryError = SurveyTemplatesIdDetailHandler400


export function useSurveyTemplatesIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError = SurveyTemplatesIdDetailHandler400>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSurveyTemplatesIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError = SurveyTemplatesIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSurveyTemplatesIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError = SurveyTemplatesIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useSurveyTemplatesIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError = SurveyTemplatesIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof surveyTemplatesIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSurveyTemplatesIdDetailHandlerSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ListHandler
 */
export const listSurveyTemplate = (
    listRequest: ListRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PagedResponseAppDomainSurveysSchemasSurveyTemplateListItem>(
      {url: `/survey-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listRequest, signal
    },
      );
    }
  



export const getListSurveyTemplateQueryKey = (listRequest?: ListRequest,) => {
    return [
    `/survey-templates`, listRequest
    ] as const;
    }

    
export const getListSurveyTemplateQueryOptions = <TData = Awaited<ReturnType<typeof listSurveyTemplate>>, TError = ListSurveyTemplate400>(listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSurveyTemplateQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSurveyTemplate>>> = ({ signal }) => listSurveyTemplate(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSurveyTemplateQueryResult = NonNullable<Awaited<ReturnType<typeof listSurveyTemplate>>>
export type ListSurveyTemplateQueryError = ListSurveyTemplate400


export function useListSurveyTemplate<TData = Awaited<ReturnType<typeof listSurveyTemplate>>, TError = ListSurveyTemplate400>(
 listRequest: ListRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSurveyTemplate>>,
          TError,
          Awaited<ReturnType<typeof listSurveyTemplate>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSurveyTemplate<TData = Awaited<ReturnType<typeof listSurveyTemplate>>, TError = ListSurveyTemplate400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSurveyTemplate>>,
          TError,
          Awaited<ReturnType<typeof listSurveyTemplate>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSurveyTemplate<TData = Awaited<ReturnType<typeof listSurveyTemplate>>, TError = ListSurveyTemplate400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListSurveyTemplate<TData = Awaited<ReturnType<typeof listSurveyTemplate>>, TError = ListSurveyTemplate400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSurveyTemplateQueryOptions(listRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getListSurveyTemplateSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listSurveyTemplate>>, TError = ListSurveyTemplate400>(listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSurveyTemplateQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSurveyTemplate>>> = ({ signal }) => listSurveyTemplate(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSurveyTemplateSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listSurveyTemplate>>>
export type ListSurveyTemplateSuspenseQueryError = ListSurveyTemplate400


export function useListSurveyTemplateSuspense<TData = Awaited<ReturnType<typeof listSurveyTemplate>>, TError = ListSurveyTemplate400>(
 listRequest: ListRequest, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSurveyTemplateSuspense<TData = Awaited<ReturnType<typeof listSurveyTemplate>>, TError = ListSurveyTemplate400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSurveyTemplateSuspense<TData = Awaited<ReturnType<typeof listSurveyTemplate>>, TError = ListSurveyTemplate400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListSurveyTemplateSuspense<TData = Awaited<ReturnType<typeof listSurveyTemplate>>, TError = ListSurveyTemplate400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSurveyTemplate>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSurveyTemplateSuspenseQueryOptions(listRequest,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




