/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_Vessel operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { VesselListItem } from "@/openapi/litestarAPI.schemas";
import { VesselType, PropulsionType, HullMaterial } from "@/openapi/litestarAPI.schemas";

export const vesselColumnDefs = createColumnBuilder<VesselListItem>()
  .text("name", { header: "Name", sortable: true, filterable: true })
  .enum("vessel_type", { header: "Vessel Type", filterable: true, options: Object.values(VesselType) })
  .enum("propulsion_type", { header: "Propulsion Type", filterable: true, options: Object.values(PropulsionType) })
  .enum("hull_material", { header: "Hull Material", filterable: true, options: Object.values(HullMaterial) })
  .number("year_built", { header: "Year Built", sortable: true, filterable: true })
  .datetime("created_at", { header: "Created", sortable: true, filterable: true, hideOnMobile: true })
  .build();

export const VesselSortableColumn = {
  created_at: 'created_at',
  name: 'name',
  year_built: 'year_built',
} as const;

export const VesselFilterableColumn = {
  created_at: 'created_at',
  hull_material: 'hull_material',
  name: 'name',
  propulsion_type: 'propulsion_type',
  vessel_type: 'vessel_type',
  year_built: 'year_built',
} as const;
