/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ListRequest,
  ListVessel400,
  PagedResponseAppDomainVesselsSchemasVesselListItem,
  VesselDetail,
  VesselsIdDetailHandler400
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary DetailHandler
 */
export const vesselsIdDetailHandler = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<VesselDetail>(
      {url: `/vessels/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getVesselsIdDetailHandlerQueryKey = (id?: string,) => {
    return [
    `/vessels/${id}`
    ] as const;
    }

    
export const getVesselsIdDetailHandlerQueryOptions = <TData = Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError = VesselsIdDetailHandler400>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVesselsIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof vesselsIdDetailHandler>>> = ({ signal }) => vesselsIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VesselsIdDetailHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof vesselsIdDetailHandler>>>
export type VesselsIdDetailHandlerQueryError = VesselsIdDetailHandler400


export function useVesselsIdDetailHandler<TData = Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError = VesselsIdDetailHandler400>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vesselsIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof vesselsIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVesselsIdDetailHandler<TData = Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError = VesselsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vesselsIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof vesselsIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVesselsIdDetailHandler<TData = Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError = VesselsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useVesselsIdDetailHandler<TData = Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError = VesselsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVesselsIdDetailHandlerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getVesselsIdDetailHandlerSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError = VesselsIdDetailHandler400>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVesselsIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof vesselsIdDetailHandler>>> = ({ signal }) => vesselsIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VesselsIdDetailHandlerSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof vesselsIdDetailHandler>>>
export type VesselsIdDetailHandlerSuspenseQueryError = VesselsIdDetailHandler400


export function useVesselsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError = VesselsIdDetailHandler400>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVesselsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError = VesselsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVesselsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError = VesselsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useVesselsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError = VesselsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof vesselsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVesselsIdDetailHandlerSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ListHandler
 */
export const listVessel = (
    listRequest: ListRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PagedResponseAppDomainVesselsSchemasVesselListItem>(
      {url: `/vessels`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listRequest, signal
    },
      );
    }
  



export const getListVesselQueryKey = (listRequest?: ListRequest,) => {
    return [
    `/vessels`, listRequest
    ] as const;
    }

    
export const getListVesselQueryOptions = <TData = Awaited<ReturnType<typeof listVessel>>, TError = ListVessel400>(listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVesselQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVessel>>> = ({ signal }) => listVessel(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVesselQueryResult = NonNullable<Awaited<ReturnType<typeof listVessel>>>
export type ListVesselQueryError = ListVessel400


export function useListVessel<TData = Awaited<ReturnType<typeof listVessel>>, TError = ListVessel400>(
 listRequest: ListRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVessel>>,
          TError,
          Awaited<ReturnType<typeof listVessel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVessel<TData = Awaited<ReturnType<typeof listVessel>>, TError = ListVessel400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVessel>>,
          TError,
          Awaited<ReturnType<typeof listVessel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVessel<TData = Awaited<ReturnType<typeof listVessel>>, TError = ListVessel400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListVessel<TData = Awaited<ReturnType<typeof listVessel>>, TError = ListVessel400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVesselQueryOptions(listRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getListVesselSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listVessel>>, TError = ListVessel400>(listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVesselQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVessel>>> = ({ signal }) => listVessel(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVesselSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listVessel>>>
export type ListVesselSuspenseQueryError = ListVessel400


export function useListVesselSuspense<TData = Awaited<ReturnType<typeof listVessel>>, TError = ListVessel400>(
 listRequest: ListRequest, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVesselSuspense<TData = Awaited<ReturnType<typeof listVessel>>, TError = ListVessel400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVesselSuspense<TData = Awaited<ReturnType<typeof listVessel>>, TError = ListVessel400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListVesselSuspense<TData = Awaited<ReturnType<typeof listVessel>>, TError = ListVessel400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVessel>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVesselSuspenseQueryOptions(listRequest,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




