/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  LocalDownloadBucketKeyLocalDownload200,
  LocalDownloadBucketKeyLocalDownload400,
  LocalUploadBucketKeyLocalUpload200,
  LocalUploadBucketKeyLocalUpload400
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary LocalUpload
 */
export const localUploadBucketKeyLocalUpload = (
    bucket: string,
    key: string,
 ) => {
      
      
      return customInstance<LocalUploadBucketKeyLocalUpload200>(
      {url: `/local-upload/${bucket}/${key}`, method: 'PUT'
    },
      );
    }
  


export const getLocalUploadBucketKeyLocalUploadMutationOptions = <TError = LocalUploadBucketKeyLocalUpload400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof localUploadBucketKeyLocalUpload>>, TError,{bucket: string;key: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof localUploadBucketKeyLocalUpload>>, TError,{bucket: string;key: string}, TContext> => {

const mutationKey = ['localUploadBucketKeyLocalUpload'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof localUploadBucketKeyLocalUpload>>, {bucket: string;key: string}> = (props) => {
          const {bucket,key} = props ?? {};

          return  localUploadBucketKeyLocalUpload(bucket,key,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LocalUploadBucketKeyLocalUploadMutationResult = NonNullable<Awaited<ReturnType<typeof localUploadBucketKeyLocalUpload>>>
    
    export type LocalUploadBucketKeyLocalUploadMutationError = LocalUploadBucketKeyLocalUpload400

    /**
 * @summary LocalUpload
 */
export const useLocalUploadBucketKeyLocalUpload = <TError = LocalUploadBucketKeyLocalUpload400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof localUploadBucketKeyLocalUpload>>, TError,{bucket: string;key: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof localUploadBucketKeyLocalUpload>>,
        TError,
        {bucket: string;key: string},
        TContext
      > => {

      const mutationOptions = getLocalUploadBucketKeyLocalUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary LocalDownload
 */
export const localDownloadBucketKeyLocalDownload = (
    bucket: string,
    key: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LocalDownloadBucketKeyLocalDownload200>(
      {url: `/local-download/${bucket}/${key}`, method: 'GET', signal
    },
      );
    }
  



export const getLocalDownloadBucketKeyLocalDownloadQueryKey = (bucket?: string,
    key?: string,) => {
    return [
    `/local-download/${bucket}/${key}`
    ] as const;
    }

    
export const getLocalDownloadBucketKeyLocalDownloadQueryOptions = <TData = Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError = LocalDownloadBucketKeyLocalDownload400>(bucket: string,
    key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLocalDownloadBucketKeyLocalDownloadQueryKey(bucket,key);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>> = ({ signal }) => localDownloadBucketKeyLocalDownload(bucket,key, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(bucket && key), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LocalDownloadBucketKeyLocalDownloadQueryResult = NonNullable<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>>
export type LocalDownloadBucketKeyLocalDownloadQueryError = LocalDownloadBucketKeyLocalDownload400


export function useLocalDownloadBucketKeyLocalDownload<TData = Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError = LocalDownloadBucketKeyLocalDownload400>(
 bucket: string,
    key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>,
          TError,
          Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLocalDownloadBucketKeyLocalDownload<TData = Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError = LocalDownloadBucketKeyLocalDownload400>(
 bucket: string,
    key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>,
          TError,
          Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLocalDownloadBucketKeyLocalDownload<TData = Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError = LocalDownloadBucketKeyLocalDownload400>(
 bucket: string,
    key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary LocalDownload
 */

export function useLocalDownloadBucketKeyLocalDownload<TData = Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError = LocalDownloadBucketKeyLocalDownload400>(
 bucket: string,
    key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLocalDownloadBucketKeyLocalDownloadQueryOptions(bucket,key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getLocalDownloadBucketKeyLocalDownloadSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError = LocalDownloadBucketKeyLocalDownload400>(bucket: string,
    key: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLocalDownloadBucketKeyLocalDownloadQueryKey(bucket,key);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>> = ({ signal }) => localDownloadBucketKeyLocalDownload(bucket,key, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LocalDownloadBucketKeyLocalDownloadSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>>
export type LocalDownloadBucketKeyLocalDownloadSuspenseQueryError = LocalDownloadBucketKeyLocalDownload400


export function useLocalDownloadBucketKeyLocalDownloadSuspense<TData = Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError = LocalDownloadBucketKeyLocalDownload400>(
 bucket: string,
    key: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLocalDownloadBucketKeyLocalDownloadSuspense<TData = Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError = LocalDownloadBucketKeyLocalDownload400>(
 bucket: string,
    key: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLocalDownloadBucketKeyLocalDownloadSuspense<TData = Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError = LocalDownloadBucketKeyLocalDownload400>(
 bucket: string,
    key: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary LocalDownload
 */

export function useLocalDownloadBucketKeyLocalDownloadSuspense<TData = Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError = LocalDownloadBucketKeyLocalDownload400>(
 bucket: string,
    key: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof localDownloadBucketKeyLocalDownload>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLocalDownloadBucketKeyLocalDownloadSuspenseQueryOptions(bucket,key,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




