/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  PublicInvoiceDetail,
  PublicInvoicesAccessTokenGetPublicInvoice400
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary GetPublicInvoice
 */
export const publicInvoicesAccessTokenGetPublicInvoice = (
    accessToken: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicInvoiceDetail>(
      {url: `/public/invoices/${accessToken}`, method: 'GET', signal
    },
      );
    }
  



export const getPublicInvoicesAccessTokenGetPublicInvoiceQueryKey = (accessToken?: string,) => {
    return [
    `/public/invoices/${accessToken}`
    ] as const;
    }

    
export const getPublicInvoicesAccessTokenGetPublicInvoiceQueryOptions = <TData = Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError = PublicInvoicesAccessTokenGetPublicInvoice400>(accessToken: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicInvoicesAccessTokenGetPublicInvoiceQueryKey(accessToken);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>> = ({ signal }) => publicInvoicesAccessTokenGetPublicInvoice(accessToken, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(accessToken), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicInvoicesAccessTokenGetPublicInvoiceQueryResult = NonNullable<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>>
export type PublicInvoicesAccessTokenGetPublicInvoiceQueryError = PublicInvoicesAccessTokenGetPublicInvoice400


export function usePublicInvoicesAccessTokenGetPublicInvoice<TData = Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError = PublicInvoicesAccessTokenGetPublicInvoice400>(
 accessToken: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>,
          TError,
          Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicInvoicesAccessTokenGetPublicInvoice<TData = Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError = PublicInvoicesAccessTokenGetPublicInvoice400>(
 accessToken: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>,
          TError,
          Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicInvoicesAccessTokenGetPublicInvoice<TData = Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError = PublicInvoicesAccessTokenGetPublicInvoice400>(
 accessToken: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetPublicInvoice
 */

export function usePublicInvoicesAccessTokenGetPublicInvoice<TData = Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError = PublicInvoicesAccessTokenGetPublicInvoice400>(
 accessToken: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicInvoicesAccessTokenGetPublicInvoiceQueryOptions(accessToken,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPublicInvoicesAccessTokenGetPublicInvoiceSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError = PublicInvoicesAccessTokenGetPublicInvoice400>(accessToken: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicInvoicesAccessTokenGetPublicInvoiceQueryKey(accessToken);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>> = ({ signal }) => publicInvoicesAccessTokenGetPublicInvoice(accessToken, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicInvoicesAccessTokenGetPublicInvoiceSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>>
export type PublicInvoicesAccessTokenGetPublicInvoiceSuspenseQueryError = PublicInvoicesAccessTokenGetPublicInvoice400


export function usePublicInvoicesAccessTokenGetPublicInvoiceSuspense<TData = Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError = PublicInvoicesAccessTokenGetPublicInvoice400>(
 accessToken: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicInvoicesAccessTokenGetPublicInvoiceSuspense<TData = Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError = PublicInvoicesAccessTokenGetPublicInvoice400>(
 accessToken: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicInvoicesAccessTokenGetPublicInvoiceSuspense<TData = Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError = PublicInvoicesAccessTokenGetPublicInvoice400>(
 accessToken: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetPublicInvoice
 */

export function usePublicInvoicesAccessTokenGetPublicInvoiceSuspense<TData = Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError = PublicInvoicesAccessTokenGetPublicInvoice400>(
 accessToken: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof publicInvoicesAccessTokenGetPublicInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicInvoicesAccessTokenGetPublicInvoiceSuspenseQueryOptions(accessToken,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




