/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthLogoutLogout201,
  AuthMagicLinkRequestRequestMagicLink201,
  AuthMagicLinkRequestRequestMagicLink400,
  AuthMagicLinkVerifyVerifyMagicLink200,
  AuthMagicLinkVerifyVerifyMagicLink400,
  AuthMagicLinkVerifyVerifyMagicLinkParams,
  MagicLinkRequestBody,
  MeResponse
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary RequestMagicLink
 */
export const authMagicLinkRequestRequestMagicLink = (
    magicLinkRequestBody: MagicLinkRequestBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthMagicLinkRequestRequestMagicLink201>(
      {url: `/auth/magic-link/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: magicLinkRequestBody, signal
    },
      );
    }
  


export const getAuthMagicLinkRequestRequestMagicLinkMutationOptions = <TError = AuthMagicLinkRequestRequestMagicLink400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>, TError,{data: MagicLinkRequestBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>, TError,{data: MagicLinkRequestBody}, TContext> => {

const mutationKey = ['authMagicLinkRequestRequestMagicLink'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>, {data: MagicLinkRequestBody}> = (props) => {
          const {data} = props ?? {};

          return  authMagicLinkRequestRequestMagicLink(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthMagicLinkRequestRequestMagicLinkMutationResult = NonNullable<Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>>
    export type AuthMagicLinkRequestRequestMagicLinkMutationBody = MagicLinkRequestBody
    export type AuthMagicLinkRequestRequestMagicLinkMutationError = AuthMagicLinkRequestRequestMagicLink400

    /**
 * @summary RequestMagicLink
 */
export const useAuthMagicLinkRequestRequestMagicLink = <TError = AuthMagicLinkRequestRequestMagicLink400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>, TError,{data: MagicLinkRequestBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>,
        TError,
        {data: MagicLinkRequestBody},
        TContext
      > => {

      const mutationOptions = getAuthMagicLinkRequestRequestMagicLinkMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary VerifyMagicLink
 */
export const authMagicLinkVerifyVerifyMagicLink = (
    params: AuthMagicLinkVerifyVerifyMagicLinkParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthMagicLinkVerifyVerifyMagicLink200>(
      {url: `/auth/magic-link/verify`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAuthMagicLinkVerifyVerifyMagicLinkQueryKey = (params?: AuthMagicLinkVerifyVerifyMagicLinkParams,) => {
    return [
    `/auth/magic-link/verify`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAuthMagicLinkVerifyVerifyMagicLinkQueryOptions = <TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMagicLinkVerifyVerifyMagicLinkQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>> = ({ signal }) => authMagicLinkVerifyVerifyMagicLink(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMagicLinkVerifyVerifyMagicLinkQueryResult = NonNullable<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>>
export type AuthMagicLinkVerifyVerifyMagicLinkQueryError = AuthMagicLinkVerifyVerifyMagicLink400


export function useAuthMagicLinkVerifyVerifyMagicLink<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>,
          TError,
          Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMagicLinkVerifyVerifyMagicLink<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>,
          TError,
          Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMagicLinkVerifyVerifyMagicLink<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary VerifyMagicLink
 */

export function useAuthMagicLinkVerifyVerifyMagicLink<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMagicLinkVerifyVerifyMagicLinkQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getAuthMagicLinkVerifyVerifyMagicLinkSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMagicLinkVerifyVerifyMagicLinkQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>> = ({ signal }) => authMagicLinkVerifyVerifyMagicLink(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMagicLinkVerifyVerifyMagicLinkSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>>
export type AuthMagicLinkVerifyVerifyMagicLinkSuspenseQueryError = AuthMagicLinkVerifyVerifyMagicLink400


export function useAuthMagicLinkVerifyVerifyMagicLinkSuspense<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMagicLinkVerifyVerifyMagicLinkSuspense<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMagicLinkVerifyVerifyMagicLinkSuspense<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary VerifyMagicLink
 */

export function useAuthMagicLinkVerifyVerifyMagicLinkSuspense<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMagicLinkVerifyVerifyMagicLinkSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Logout
 */
export const authLogoutLogout = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthLogoutLogout201>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      );
    }
  


export const getAuthLogoutLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogoutLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authLogoutLogout>>, TError,void, TContext> => {

const mutationKey = ['authLogoutLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogoutLogout>>, void> = () => {
          

          return  authLogoutLogout()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogoutLogout>>>
    
    export type AuthLogoutLogoutMutationError = unknown

    /**
 * @summary Logout
 */
export const useAuthLogoutLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogoutLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogoutLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthLogoutLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Me
 */
export const authMeMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<MeResponse>(
      {url: `/auth/me`, method: 'GET', signal
    },
      );
    }
  



export const getAuthMeMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }

    
export const getAuthMeMeQueryOptions = <TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMeMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMeMe>>> = ({ signal }) => authMeMe(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMeMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMeMe>>>
export type AuthMeMeQueryError = unknown


export function useAuthMeMe<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMeMe>>,
          TError,
          Awaited<ReturnType<typeof authMeMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMeMe<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMeMe>>,
          TError,
          Awaited<ReturnType<typeof authMeMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMeMe<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Me
 */

export function useAuthMeMe<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMeMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getAuthMeMeSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMeMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMeMe>>> = ({ signal }) => authMeMe(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMeMeSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof authMeMe>>>
export type AuthMeMeSuspenseQueryError = unknown


export function useAuthMeMeSuspense<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMeMeSuspense<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMeMeSuspense<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Me
 */

export function useAuthMeMeSuspense<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMeMeSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




