/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  CalendarEventDetail,
  CalendarEventsIdDetailHandler400,
  ListCalendarEvent400,
  ListRequest,
  PagedResponseAppDomainCalendarEventsSchemasCalendarEventListItem
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary DetailHandler
 */
export const calendarEventsIdDetailHandler = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CalendarEventDetail>(
      {url: `/calendar-events/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getCalendarEventsIdDetailHandlerQueryKey = (id?: string,) => {
    return [
    `/calendar-events/${id}`
    ] as const;
    }

    
export const getCalendarEventsIdDetailHandlerQueryOptions = <TData = Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError = CalendarEventsIdDetailHandler400>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCalendarEventsIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>> = ({ signal }) => calendarEventsIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CalendarEventsIdDetailHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>>
export type CalendarEventsIdDetailHandlerQueryError = CalendarEventsIdDetailHandler400


export function useCalendarEventsIdDetailHandler<TData = Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError = CalendarEventsIdDetailHandler400>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCalendarEventsIdDetailHandler<TData = Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError = CalendarEventsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCalendarEventsIdDetailHandler<TData = Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError = CalendarEventsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useCalendarEventsIdDetailHandler<TData = Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError = CalendarEventsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCalendarEventsIdDetailHandlerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getCalendarEventsIdDetailHandlerSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError = CalendarEventsIdDetailHandler400>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCalendarEventsIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>> = ({ signal }) => calendarEventsIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CalendarEventsIdDetailHandlerSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>>
export type CalendarEventsIdDetailHandlerSuspenseQueryError = CalendarEventsIdDetailHandler400


export function useCalendarEventsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError = CalendarEventsIdDetailHandler400>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCalendarEventsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError = CalendarEventsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCalendarEventsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError = CalendarEventsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useCalendarEventsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError = CalendarEventsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof calendarEventsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCalendarEventsIdDetailHandlerSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ListHandler
 */
export const listCalendarEvent = (
    listRequest: ListRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PagedResponseAppDomainCalendarEventsSchemasCalendarEventListItem>(
      {url: `/calendar-events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listRequest, signal
    },
      );
    }
  



export const getListCalendarEventQueryKey = (listRequest?: ListRequest,) => {
    return [
    `/calendar-events`, listRequest
    ] as const;
    }

    
export const getListCalendarEventQueryOptions = <TData = Awaited<ReturnType<typeof listCalendarEvent>>, TError = ListCalendarEvent400>(listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCalendarEventQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCalendarEvent>>> = ({ signal }) => listCalendarEvent(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCalendarEventQueryResult = NonNullable<Awaited<ReturnType<typeof listCalendarEvent>>>
export type ListCalendarEventQueryError = ListCalendarEvent400


export function useListCalendarEvent<TData = Awaited<ReturnType<typeof listCalendarEvent>>, TError = ListCalendarEvent400>(
 listRequest: ListRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCalendarEvent>>,
          TError,
          Awaited<ReturnType<typeof listCalendarEvent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCalendarEvent<TData = Awaited<ReturnType<typeof listCalendarEvent>>, TError = ListCalendarEvent400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCalendarEvent>>,
          TError,
          Awaited<ReturnType<typeof listCalendarEvent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCalendarEvent<TData = Awaited<ReturnType<typeof listCalendarEvent>>, TError = ListCalendarEvent400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListCalendarEvent<TData = Awaited<ReturnType<typeof listCalendarEvent>>, TError = ListCalendarEvent400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCalendarEventQueryOptions(listRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getListCalendarEventSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listCalendarEvent>>, TError = ListCalendarEvent400>(listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCalendarEventQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCalendarEvent>>> = ({ signal }) => listCalendarEvent(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCalendarEventSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listCalendarEvent>>>
export type ListCalendarEventSuspenseQueryError = ListCalendarEvent400


export function useListCalendarEventSuspense<TData = Awaited<ReturnType<typeof listCalendarEvent>>, TError = ListCalendarEvent400>(
 listRequest: ListRequest, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCalendarEventSuspense<TData = Awaited<ReturnType<typeof listCalendarEvent>>, TError = ListCalendarEvent400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCalendarEventSuspense<TData = Awaited<ReturnType<typeof listCalendarEvent>>, TError = ListCalendarEvent400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListCalendarEventSuspense<TData = Awaited<ReturnType<typeof listCalendarEvent>>, TError = ListCalendarEvent400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listCalendarEvent>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCalendarEventSuspenseQueryOptions(listRequest,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




