/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DataInvoice400,
  DataSchemaResponse,
  TimeSeriesDataRequest,
  TimeSeriesDataResponse
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary DataHandler
 */
export const dataInvoice = (
    timeSeriesDataRequest: TimeSeriesDataRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TimeSeriesDataResponse>(
      {url: `/invoices/data`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: timeSeriesDataRequest, signal
    },
      );
    }
  


export const getDataInvoiceMutationOptions = <TError = DataInvoice400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataInvoice>>, TError,{data: TimeSeriesDataRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof dataInvoice>>, TError,{data: TimeSeriesDataRequest}, TContext> => {

const mutationKey = ['dataInvoice'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dataInvoice>>, {data: TimeSeriesDataRequest}> = (props) => {
          const {data} = props ?? {};

          return  dataInvoice(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DataInvoiceMutationResult = NonNullable<Awaited<ReturnType<typeof dataInvoice>>>
    export type DataInvoiceMutationBody = TimeSeriesDataRequest
    export type DataInvoiceMutationError = DataInvoice400

    /**
 * @summary DataHandler
 */
export const useDataInvoice = <TError = DataInvoice400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dataInvoice>>, TError,{data: TimeSeriesDataRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dataInvoice>>,
        TError,
        {data: TimeSeriesDataRequest},
        TContext
      > => {

      const mutationOptions = getDataInvoiceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary DataSchemaHandler
 */
export const dataSchemaInvoice = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<DataSchemaResponse>(
      {url: `/invoices/data/schema`, method: 'GET', signal
    },
      );
    }
  



export const getDataSchemaInvoiceQueryKey = () => {
    return [
    `/invoices/data/schema`
    ] as const;
    }

    
export const getDataSchemaInvoiceQueryOptions = <TData = Awaited<ReturnType<typeof dataSchemaInvoice>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDataSchemaInvoiceQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dataSchemaInvoice>>> = ({ signal }) => dataSchemaInvoice(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DataSchemaInvoiceQueryResult = NonNullable<Awaited<ReturnType<typeof dataSchemaInvoice>>>
export type DataSchemaInvoiceQueryError = unknown


export function useDataSchemaInvoice<TData = Awaited<ReturnType<typeof dataSchemaInvoice>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dataSchemaInvoice>>,
          TError,
          Awaited<ReturnType<typeof dataSchemaInvoice>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataSchemaInvoice<TData = Awaited<ReturnType<typeof dataSchemaInvoice>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dataSchemaInvoice>>,
          TError,
          Awaited<ReturnType<typeof dataSchemaInvoice>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataSchemaInvoice<TData = Awaited<ReturnType<typeof dataSchemaInvoice>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DataSchemaHandler
 */

export function useDataSchemaInvoice<TData = Awaited<ReturnType<typeof dataSchemaInvoice>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDataSchemaInvoiceQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getDataSchemaInvoiceSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof dataSchemaInvoice>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDataSchemaInvoiceQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dataSchemaInvoice>>> = ({ signal }) => dataSchemaInvoice(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DataSchemaInvoiceSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof dataSchemaInvoice>>>
export type DataSchemaInvoiceSuspenseQueryError = unknown


export function useDataSchemaInvoiceSuspense<TData = Awaited<ReturnType<typeof dataSchemaInvoice>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataSchemaInvoiceSuspense<TData = Awaited<ReturnType<typeof dataSchemaInvoice>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDataSchemaInvoiceSuspense<TData = Awaited<ReturnType<typeof dataSchemaInvoice>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DataSchemaHandler
 */

export function useDataSchemaInvoiceSuspense<TData = Awaited<ReturnType<typeof dataSchemaInvoice>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof dataSchemaInvoice>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDataSchemaInvoiceSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




