/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ListOnboarding400,
  ListRequest,
  OnboardingConfigResponse,
  OnboardingDetail,
  OnboardingsIdDetailHandler400,
  PagedResponseAppDomainOnboardingSchemasOnboardingListItem
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary GetOnboardingConfig
 */
export const getOnboardingConfig = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<OnboardingConfigResponse>(
      {url: `/onboarding/config`, method: 'GET', signal
    },
      );
    }
  



export const getGetOnboardingConfigQueryKey = () => {
    return [
    `/onboarding/config`
    ] as const;
    }

    
export const getGetOnboardingConfigQueryOptions = <TData = Awaited<ReturnType<typeof getOnboardingConfig>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOnboardingConfigQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnboardingConfig>>> = ({ signal }) => getOnboardingConfig(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOnboardingConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getOnboardingConfig>>>
export type GetOnboardingConfigQueryError = unknown


export function useGetOnboardingConfig<TData = Awaited<ReturnType<typeof getOnboardingConfig>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOnboardingConfig>>,
          TError,
          Awaited<ReturnType<typeof getOnboardingConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOnboardingConfig<TData = Awaited<ReturnType<typeof getOnboardingConfig>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOnboardingConfig>>,
          TError,
          Awaited<ReturnType<typeof getOnboardingConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOnboardingConfig<TData = Awaited<ReturnType<typeof getOnboardingConfig>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetOnboardingConfig
 */

export function useGetOnboardingConfig<TData = Awaited<ReturnType<typeof getOnboardingConfig>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOnboardingConfigQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetOnboardingConfigSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getOnboardingConfig>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOnboardingConfigQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnboardingConfig>>> = ({ signal }) => getOnboardingConfig(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOnboardingConfigSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getOnboardingConfig>>>
export type GetOnboardingConfigSuspenseQueryError = unknown


export function useGetOnboardingConfigSuspense<TData = Awaited<ReturnType<typeof getOnboardingConfig>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOnboardingConfigSuspense<TData = Awaited<ReturnType<typeof getOnboardingConfig>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOnboardingConfigSuspense<TData = Awaited<ReturnType<typeof getOnboardingConfig>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetOnboardingConfig
 */

export function useGetOnboardingConfigSuspense<TData = Awaited<ReturnType<typeof getOnboardingConfig>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getOnboardingConfig>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOnboardingConfigSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary DetailHandler
 */
export const onboardingsIdDetailHandler = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<OnboardingDetail>(
      {url: `/onboardings/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getOnboardingsIdDetailHandlerQueryKey = (id?: string,) => {
    return [
    `/onboardings/${id}`
    ] as const;
    }

    
export const getOnboardingsIdDetailHandlerQueryOptions = <TData = Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError = OnboardingsIdDetailHandler400>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOnboardingsIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>> = ({ signal }) => onboardingsIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OnboardingsIdDetailHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>>
export type OnboardingsIdDetailHandlerQueryError = OnboardingsIdDetailHandler400


export function useOnboardingsIdDetailHandler<TData = Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError = OnboardingsIdDetailHandler400>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onboardingsIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof onboardingsIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOnboardingsIdDetailHandler<TData = Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError = OnboardingsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onboardingsIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof onboardingsIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOnboardingsIdDetailHandler<TData = Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError = OnboardingsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useOnboardingsIdDetailHandler<TData = Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError = OnboardingsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOnboardingsIdDetailHandlerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getOnboardingsIdDetailHandlerSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError = OnboardingsIdDetailHandler400>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOnboardingsIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>> = ({ signal }) => onboardingsIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OnboardingsIdDetailHandlerSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>>
export type OnboardingsIdDetailHandlerSuspenseQueryError = OnboardingsIdDetailHandler400


export function useOnboardingsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError = OnboardingsIdDetailHandler400>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOnboardingsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError = OnboardingsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOnboardingsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError = OnboardingsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useOnboardingsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError = OnboardingsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof onboardingsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOnboardingsIdDetailHandlerSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ListHandler
 */
export const listOnboarding = (
    listRequest: ListRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PagedResponseAppDomainOnboardingSchemasOnboardingListItem>(
      {url: `/onboardings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listRequest, signal
    },
      );
    }
  



export const getListOnboardingQueryKey = (listRequest?: ListRequest,) => {
    return [
    `/onboardings`, listRequest
    ] as const;
    }

    
export const getListOnboardingQueryOptions = <TData = Awaited<ReturnType<typeof listOnboarding>>, TError = ListOnboarding400>(listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOnboardingQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOnboarding>>> = ({ signal }) => listOnboarding(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListOnboardingQueryResult = NonNullable<Awaited<ReturnType<typeof listOnboarding>>>
export type ListOnboardingQueryError = ListOnboarding400


export function useListOnboarding<TData = Awaited<ReturnType<typeof listOnboarding>>, TError = ListOnboarding400>(
 listRequest: ListRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOnboarding>>,
          TError,
          Awaited<ReturnType<typeof listOnboarding>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOnboarding<TData = Awaited<ReturnType<typeof listOnboarding>>, TError = ListOnboarding400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOnboarding>>,
          TError,
          Awaited<ReturnType<typeof listOnboarding>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOnboarding<TData = Awaited<ReturnType<typeof listOnboarding>>, TError = ListOnboarding400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListOnboarding<TData = Awaited<ReturnType<typeof listOnboarding>>, TError = ListOnboarding400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListOnboardingQueryOptions(listRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getListOnboardingSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listOnboarding>>, TError = ListOnboarding400>(listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOnboardingQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOnboarding>>> = ({ signal }) => listOnboarding(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListOnboardingSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listOnboarding>>>
export type ListOnboardingSuspenseQueryError = ListOnboarding400


export function useListOnboardingSuspense<TData = Awaited<ReturnType<typeof listOnboarding>>, TError = ListOnboarding400>(
 listRequest: ListRequest, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOnboardingSuspense<TData = Awaited<ReturnType<typeof listOnboarding>>, TError = ListOnboarding400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOnboardingSuspense<TData = Awaited<ReturnType<typeof listOnboarding>>, TError = ListOnboarding400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListOnboardingSuspense<TData = Awaited<ReturnType<typeof listOnboarding>>, TError = ListOnboarding400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listOnboarding>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListOnboardingSuspenseQueryOptions(listRequest,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




