/**
 * Pre-Orval codegen — fetches CRUD metadata and generates the operations
 * override so that POST-based list endpoints are treated as queries.
 *
 * Run: npx tsx scripts/generate-orval-operations.ts
 * Must run BEFORE orval (backend must be live at :8000).
 */

import { writeFileSync } from "fs";
import { join } from "path";

const METADATA_URL =
  process.env.METADATA_URL ?? "http://localhost:8000/schema/crud-metadata";
const OUTPUT_PATH = join(import.meta.dirname, "../src/openapi/orval-operations.gen.ts");

async function main() {
  const res = await fetch(METADATA_URL);
  if (!res.ok) {
    console.error(`Failed to fetch CRUD metadata: ${res.status}`);
    process.exit(1);
  }

  const metadata: Record<string, unknown> = await res.json();
  const operationIds = Object.keys(metadata);

  const entries = operationIds
    .map((id) => `  ${id}: { query: { useQuery: true } },`)
    .join("\n");

  const content = `/**
 * Generated by generate-orval-operations.ts — DO NOT EDIT
 * Maps CRUD list operations (POST) to query hooks instead of mutations.
 */
export const crudOperations: Record<string, { query: { useQuery: boolean } }> = {
${entries}
};
`;

  writeFileSync(OUTPUT_PATH, content);
  console.log(`  ✓ Generated ${operationIds.length} operation override(s)`);
}

main().catch((err) => {
  console.error("Orval operations codegen failed:", err);
  process.exit(1);
});
