/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_InvoiceLineItem operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { InvoiceLineItemListItem } from "@/openapi/litestarAPI.schemas";


export const invoiceLineItemColumnDefs = createColumnBuilder<InvoiceLineItemListItem>()
  .text("description", { header: "Description", className: "max-w-[200px]" })
  .number("quantity", { header: "Quantity" })
  .currency("unit_price_cents", { header: "Unit Price" })
  .number("sort_order", { header: "Sort Order", sortable: true, filterable: true })
  .datetime("created_at", { header: "Created", sortable: true, hideOnMobile: true })
  .build();

export const InvoiceLineItemSortableColumn = {
  created_at: 'created_at',
  sort_order: 'sort_order',
} as const;

export const InvoiceLineItemFilterableColumn = {
  invoice_id: 'invoice_id',
  sort_order: 'sort_order',
} as const;
