/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AcceptTosData,
  AttachExternalAccountData,
  BillingConnectAccountExternalAccountsAttachExternalAccount400,
  BillingConnectAccountIdentityDocumentsUploadIdentityDocument400,
  BillingConnectAccountIdentityDocumentsUploadIdentityDocumentBody,
  BillingConnectAccountTosAcceptanceAcceptConnectAccountTos400,
  BillingConnectAccountUpdateConnectAccount400,
  ConnectAccountRequirementsResponse,
  ConnectAccountResponse,
  ConnectAccountStatusResponse,
  ExternalAccountResponse,
  IdentityDocumentResponse,
  UpdateConnectAccountData
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary GetConnectAccount
 */
export const billingConnectAccountGetConnectAccount = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ConnectAccountStatusResponse>(
      {url: `/billing/connect/account`, method: 'GET', signal
    },
      );
    }
  



export const getBillingConnectAccountGetConnectAccountQueryKey = () => {
    return [
    `/billing/connect/account`
    ] as const;
    }

    
export const getBillingConnectAccountGetConnectAccountQueryOptions = <TData = Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingConnectAccountGetConnectAccountQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>> = ({ signal }) => billingConnectAccountGetConnectAccount(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BillingConnectAccountGetConnectAccountQueryResult = NonNullable<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>>
export type BillingConnectAccountGetConnectAccountQueryError = unknown


export function useBillingConnectAccountGetConnectAccount<TData = Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>,
          TError,
          Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBillingConnectAccountGetConnectAccount<TData = Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>,
          TError,
          Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBillingConnectAccountGetConnectAccount<TData = Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetConnectAccount
 */

export function useBillingConnectAccountGetConnectAccount<TData = Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBillingConnectAccountGetConnectAccountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getBillingConnectAccountGetConnectAccountSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingConnectAccountGetConnectAccountQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>> = ({ signal }) => billingConnectAccountGetConnectAccount(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BillingConnectAccountGetConnectAccountSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>>
export type BillingConnectAccountGetConnectAccountSuspenseQueryError = unknown


export function useBillingConnectAccountGetConnectAccountSuspense<TData = Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBillingConnectAccountGetConnectAccountSuspense<TData = Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBillingConnectAccountGetConnectAccountSuspense<TData = Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetConnectAccount
 */

export function useBillingConnectAccountGetConnectAccountSuspense<TData = Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountGetConnectAccount>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBillingConnectAccountGetConnectAccountSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary CreateConnectAccount
 */
export const billingConnectAccountCreateConnectAccount = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ConnectAccountResponse>(
      {url: `/billing/connect/account`, method: 'POST', signal
    },
      );
    }
  


export const getBillingConnectAccountCreateConnectAccountMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountCreateConnectAccount>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountCreateConnectAccount>>, TError,void, TContext> => {

const mutationKey = ['billingConnectAccountCreateConnectAccount'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof billingConnectAccountCreateConnectAccount>>, void> = () => {
          

          return  billingConnectAccountCreateConnectAccount()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BillingConnectAccountCreateConnectAccountMutationResult = NonNullable<Awaited<ReturnType<typeof billingConnectAccountCreateConnectAccount>>>
    
    export type BillingConnectAccountCreateConnectAccountMutationError = unknown

    /**
 * @summary CreateConnectAccount
 */
export const useBillingConnectAccountCreateConnectAccount = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountCreateConnectAccount>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof billingConnectAccountCreateConnectAccount>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getBillingConnectAccountCreateConnectAccountMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary UpdateConnectAccount
 */
export const billingConnectAccountUpdateConnectAccount = (
    updateConnectAccountData: UpdateConnectAccountData,
 ) => {
      
      
      return customInstance<ConnectAccountResponse>(
      {url: `/billing/connect/account`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateConnectAccountData
    },
      );
    }
  


export const getBillingConnectAccountUpdateConnectAccountMutationOptions = <TError = BillingConnectAccountUpdateConnectAccount400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountUpdateConnectAccount>>, TError,{data: UpdateConnectAccountData}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountUpdateConnectAccount>>, TError,{data: UpdateConnectAccountData}, TContext> => {

const mutationKey = ['billingConnectAccountUpdateConnectAccount'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof billingConnectAccountUpdateConnectAccount>>, {data: UpdateConnectAccountData}> = (props) => {
          const {data} = props ?? {};

          return  billingConnectAccountUpdateConnectAccount(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BillingConnectAccountUpdateConnectAccountMutationResult = NonNullable<Awaited<ReturnType<typeof billingConnectAccountUpdateConnectAccount>>>
    export type BillingConnectAccountUpdateConnectAccountMutationBody = UpdateConnectAccountData
    export type BillingConnectAccountUpdateConnectAccountMutationError = BillingConnectAccountUpdateConnectAccount400

    /**
 * @summary UpdateConnectAccount
 */
export const useBillingConnectAccountUpdateConnectAccount = <TError = BillingConnectAccountUpdateConnectAccount400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountUpdateConnectAccount>>, TError,{data: UpdateConnectAccountData}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof billingConnectAccountUpdateConnectAccount>>,
        TError,
        {data: UpdateConnectAccountData},
        TContext
      > => {

      const mutationOptions = getBillingConnectAccountUpdateConnectAccountMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary GetConnectAccountRequirements
 */
export const billingConnectAccountRequirementsGetConnectAccountRequirements = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ConnectAccountRequirementsResponse>(
      {url: `/billing/connect/account/requirements`, method: 'GET', signal
    },
      );
    }
  



export const getBillingConnectAccountRequirementsGetConnectAccountRequirementsQueryKey = () => {
    return [
    `/billing/connect/account/requirements`
    ] as const;
    }

    
export const getBillingConnectAccountRequirementsGetConnectAccountRequirementsQueryOptions = <TData = Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingConnectAccountRequirementsGetConnectAccountRequirementsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>> = ({ signal }) => billingConnectAccountRequirementsGetConnectAccountRequirements(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BillingConnectAccountRequirementsGetConnectAccountRequirementsQueryResult = NonNullable<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>>
export type BillingConnectAccountRequirementsGetConnectAccountRequirementsQueryError = unknown


export function useBillingConnectAccountRequirementsGetConnectAccountRequirements<TData = Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>,
          TError,
          Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBillingConnectAccountRequirementsGetConnectAccountRequirements<TData = Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>,
          TError,
          Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBillingConnectAccountRequirementsGetConnectAccountRequirements<TData = Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetConnectAccountRequirements
 */

export function useBillingConnectAccountRequirementsGetConnectAccountRequirements<TData = Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBillingConnectAccountRequirementsGetConnectAccountRequirementsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getBillingConnectAccountRequirementsGetConnectAccountRequirementsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingConnectAccountRequirementsGetConnectAccountRequirementsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>> = ({ signal }) => billingConnectAccountRequirementsGetConnectAccountRequirements(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BillingConnectAccountRequirementsGetConnectAccountRequirementsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>>
export type BillingConnectAccountRequirementsGetConnectAccountRequirementsSuspenseQueryError = unknown


export function useBillingConnectAccountRequirementsGetConnectAccountRequirementsSuspense<TData = Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBillingConnectAccountRequirementsGetConnectAccountRequirementsSuspense<TData = Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBillingConnectAccountRequirementsGetConnectAccountRequirementsSuspense<TData = Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetConnectAccountRequirements
 */

export function useBillingConnectAccountRequirementsGetConnectAccountRequirementsSuspense<TData = Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof billingConnectAccountRequirementsGetConnectAccountRequirements>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBillingConnectAccountRequirementsGetConnectAccountRequirementsSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary AcceptConnectAccountTos
 */
export const billingConnectAccountTosAcceptanceAcceptConnectAccountTos = (
    acceptTosData: AcceptTosData,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ConnectAccountResponse>(
      {url: `/billing/connect/account/tos-acceptance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: acceptTosData, signal
    },
      );
    }
  


export const getBillingConnectAccountTosAcceptanceAcceptConnectAccountTosMutationOptions = <TError = BillingConnectAccountTosAcceptanceAcceptConnectAccountTos400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountTosAcceptanceAcceptConnectAccountTos>>, TError,{data: AcceptTosData}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountTosAcceptanceAcceptConnectAccountTos>>, TError,{data: AcceptTosData}, TContext> => {

const mutationKey = ['billingConnectAccountTosAcceptanceAcceptConnectAccountTos'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof billingConnectAccountTosAcceptanceAcceptConnectAccountTos>>, {data: AcceptTosData}> = (props) => {
          const {data} = props ?? {};

          return  billingConnectAccountTosAcceptanceAcceptConnectAccountTos(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BillingConnectAccountTosAcceptanceAcceptConnectAccountTosMutationResult = NonNullable<Awaited<ReturnType<typeof billingConnectAccountTosAcceptanceAcceptConnectAccountTos>>>
    export type BillingConnectAccountTosAcceptanceAcceptConnectAccountTosMutationBody = AcceptTosData
    export type BillingConnectAccountTosAcceptanceAcceptConnectAccountTosMutationError = BillingConnectAccountTosAcceptanceAcceptConnectAccountTos400

    /**
 * @summary AcceptConnectAccountTos
 */
export const useBillingConnectAccountTosAcceptanceAcceptConnectAccountTos = <TError = BillingConnectAccountTosAcceptanceAcceptConnectAccountTos400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountTosAcceptanceAcceptConnectAccountTos>>, TError,{data: AcceptTosData}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof billingConnectAccountTosAcceptanceAcceptConnectAccountTos>>,
        TError,
        {data: AcceptTosData},
        TContext
      > => {

      const mutationOptions = getBillingConnectAccountTosAcceptanceAcceptConnectAccountTosMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary AttachExternalAccount
 */
export const billingConnectAccountExternalAccountsAttachExternalAccount = (
    attachExternalAccountData: AttachExternalAccountData,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ExternalAccountResponse>(
      {url: `/billing/connect/account/external-accounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attachExternalAccountData, signal
    },
      );
    }
  


export const getBillingConnectAccountExternalAccountsAttachExternalAccountMutationOptions = <TError = BillingConnectAccountExternalAccountsAttachExternalAccount400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountExternalAccountsAttachExternalAccount>>, TError,{data: AttachExternalAccountData}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountExternalAccountsAttachExternalAccount>>, TError,{data: AttachExternalAccountData}, TContext> => {

const mutationKey = ['billingConnectAccountExternalAccountsAttachExternalAccount'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof billingConnectAccountExternalAccountsAttachExternalAccount>>, {data: AttachExternalAccountData}> = (props) => {
          const {data} = props ?? {};

          return  billingConnectAccountExternalAccountsAttachExternalAccount(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BillingConnectAccountExternalAccountsAttachExternalAccountMutationResult = NonNullable<Awaited<ReturnType<typeof billingConnectAccountExternalAccountsAttachExternalAccount>>>
    export type BillingConnectAccountExternalAccountsAttachExternalAccountMutationBody = AttachExternalAccountData
    export type BillingConnectAccountExternalAccountsAttachExternalAccountMutationError = BillingConnectAccountExternalAccountsAttachExternalAccount400

    /**
 * @summary AttachExternalAccount
 */
export const useBillingConnectAccountExternalAccountsAttachExternalAccount = <TError = BillingConnectAccountExternalAccountsAttachExternalAccount400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountExternalAccountsAttachExternalAccount>>, TError,{data: AttachExternalAccountData}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof billingConnectAccountExternalAccountsAttachExternalAccount>>,
        TError,
        {data: AttachExternalAccountData},
        TContext
      > => {

      const mutationOptions = getBillingConnectAccountExternalAccountsAttachExternalAccountMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary UploadIdentityDocument
 */
export const billingConnectAccountIdentityDocumentsUploadIdentityDocument = (
    billingConnectAccountIdentityDocumentsUploadIdentityDocumentBody: BillingConnectAccountIdentityDocumentsUploadIdentityDocumentBody,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
if(billingConnectAccountIdentityDocumentsUploadIdentityDocumentBody.file !== undefined) {
 formData.append(`file`, billingConnectAccountIdentityDocumentsUploadIdentityDocumentBody.file)
 }

      return customInstance<IdentityDocumentResponse>(
      {url: `/billing/connect/account/identity-documents`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getBillingConnectAccountIdentityDocumentsUploadIdentityDocumentMutationOptions = <TError = BillingConnectAccountIdentityDocumentsUploadIdentityDocument400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountIdentityDocumentsUploadIdentityDocument>>, TError,{data: BillingConnectAccountIdentityDocumentsUploadIdentityDocumentBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountIdentityDocumentsUploadIdentityDocument>>, TError,{data: BillingConnectAccountIdentityDocumentsUploadIdentityDocumentBody}, TContext> => {

const mutationKey = ['billingConnectAccountIdentityDocumentsUploadIdentityDocument'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof billingConnectAccountIdentityDocumentsUploadIdentityDocument>>, {data: BillingConnectAccountIdentityDocumentsUploadIdentityDocumentBody}> = (props) => {
          const {data} = props ?? {};

          return  billingConnectAccountIdentityDocumentsUploadIdentityDocument(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BillingConnectAccountIdentityDocumentsUploadIdentityDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof billingConnectAccountIdentityDocumentsUploadIdentityDocument>>>
    export type BillingConnectAccountIdentityDocumentsUploadIdentityDocumentMutationBody = BillingConnectAccountIdentityDocumentsUploadIdentityDocumentBody
    export type BillingConnectAccountIdentityDocumentsUploadIdentityDocumentMutationError = BillingConnectAccountIdentityDocumentsUploadIdentityDocument400

    /**
 * @summary UploadIdentityDocument
 */
export const useBillingConnectAccountIdentityDocumentsUploadIdentityDocument = <TError = BillingConnectAccountIdentityDocumentsUploadIdentityDocument400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof billingConnectAccountIdentityDocumentsUploadIdentityDocument>>, TError,{data: BillingConnectAccountIdentityDocumentsUploadIdentityDocumentBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof billingConnectAccountIdentityDocumentsUploadIdentityDocument>>,
        TError,
        {data: BillingConnectAccountIdentityDocumentsUploadIdentityDocumentBody},
        TContext
      > => {

      const mutationOptions = getBillingConnectAccountIdentityDocumentsUploadIdentityDocumentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    