/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DemoSwitchRoleSwitchRole400,
  MeResponse,
  SwitchRoleBody
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary SwitchRole
 */
export const demoSwitchRoleSwitchRole = (
    switchRoleBody: SwitchRoleBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MeResponse>(
      {url: `/demo/switch-role`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: switchRoleBody, signal
    },
      );
    }
  


export const getDemoSwitchRoleSwitchRoleMutationOptions = <TError = DemoSwitchRoleSwitchRole400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof demoSwitchRoleSwitchRole>>, TError,{data: SwitchRoleBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof demoSwitchRoleSwitchRole>>, TError,{data: SwitchRoleBody}, TContext> => {

const mutationKey = ['demoSwitchRoleSwitchRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof demoSwitchRoleSwitchRole>>, {data: SwitchRoleBody}> = (props) => {
          const {data} = props ?? {};

          return  demoSwitchRoleSwitchRole(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DemoSwitchRoleSwitchRoleMutationResult = NonNullable<Awaited<ReturnType<typeof demoSwitchRoleSwitchRole>>>
    export type DemoSwitchRoleSwitchRoleMutationBody = SwitchRoleBody
    export type DemoSwitchRoleSwitchRoleMutationError = DemoSwitchRoleSwitchRole400

    /**
 * @summary SwitchRole
 */
export const useDemoSwitchRoleSwitchRole = <TError = DemoSwitchRoleSwitchRole400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof demoSwitchRoleSwitchRole>>, TError,{data: SwitchRoleBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof demoSwitchRoleSwitchRole>>,
        TError,
        {data: SwitchRoleBody},
        TContext
      > => {

      const mutationOptions = getDemoSwitchRoleSwitchRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    