/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_Subscription operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { SubscriptionListItem } from "@/openapi/litestarAPI.schemas";
import { SubscriptionPlan, SubscriptionStatus } from "@/openapi/litestarAPI.schemas";

export const subscriptionColumnDefs = createColumnBuilder<SubscriptionListItem>()
  .enum("plan", { header: "Plan", filterable: true, options: Object.values(SubscriptionPlan) })
  .status("state", { header: "State", filterable: true, options: Object.values(SubscriptionStatus) })
  .datetime("trial_ends_at", { header: "Trial Ends", hideOnMobile: true })
  .datetime("current_period_end", { header: "Current Period End", sortable: true, hideOnMobile: true })
  .datetime("created_at", { header: "Created", sortable: true, filterable: true, hideOnMobile: true })
  .build();

export const SubscriptionSortableColumn = {
  created_at: 'created_at',
  current_period_end: 'current_period_end',
} as const;

export const SubscriptionFilterableColumn = {
  created_at: 'created_at',
  plan: 'plan',
  state: 'state',
} as const;
