"""move_service_type_to_guide

Revision ID: 5a6763b9cf9b
Revises: 8b1186520fa5
Create Date: 2026-05-25 15:57:40.504736+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op
from app.domain.pricing_guides.enums import ServiceType
from app.utils.textenum import TextEnum

# revision identifiers, used by Alembic.
revision: str = "5a6763b9cf9b"
down_revision: str | None = "8b1186520fa5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("pricing_guides", sa.Column("service_type", TextEnum(ServiceType), nullable=True))
    op.execute(
        """
        UPDATE pricing_guides g
        SET service_type = COALESCE(
            (
                SELECT t.service_type
                FROM pricing_tiers t
                WHERE t.guide_id = g.id AND t.service_type IS NOT NULL
                ORDER BY t.sort_order, t.id
                LIMIT 1
            ),
            'pre_purchase'
        )
        """
    )
    op.alter_column("pricing_guides", "service_type", nullable=False)
    op.drop_index(
        op.f("uq_pricing_guides_active_per_user"),
        table_name="pricing_guides",
        postgresql_where="(is_active AND (deleted_at IS NULL))",
    )
    op.create_index(
        "uq_pricing_guides_active_per_user_service",
        "pricing_guides",
        ["user_id", "service_type"],
        unique=True,
        postgresql_where=sa.text("is_active AND deleted_at IS NULL"),
    )
    op.drop_column("pricing_tiers", "service_type")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pricing_tiers", sa.Column("service_type", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(
        "uq_pricing_guides_active_per_user_service",
        table_name="pricing_guides",
        postgresql_where=sa.text("is_active AND deleted_at IS NULL"),
    )
    op.create_index(
        op.f("uq_pricing_guides_active_per_user"),
        "pricing_guides",
        ["user_id"],
        unique=True,
        postgresql_where="(is_active AND (deleted_at IS NULL))",
    )
    op.drop_column("pricing_guides", "service_type")
    # ### end Alembic commands ###
