"""drop_findings_and_recommendations

Revision ID: 169814776707
Revises: b7d6e601a599
Create Date: 2026-05-09 20:37:08.674036+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "169814776707"
down_revision: str | None = "b7d6e601a599"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendations_finding_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_findings_survey_id"), table_name="findings")
    op.drop_table("findings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendations",
        sa.Column("finding_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_completed", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"], ["findings.id"], name=op.f("recommendations_finding_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("recommendations_pkey")),
    )
    op.create_index(op.f("ix_recommendations_finding_id"), "recommendations", ["finding_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("survey_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("severity", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "is_pre_existing", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("section_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("location", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["survey_id"], ["surveys.id"], name=op.f("findings_survey_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("findings_pkey")),
    )
    op.create_index(op.f("ix_findings_survey_id"), "findings", ["survey_id"], unique=False)
    # ### end Alembic commands ###
