"""add_dashboard

Revision ID: 7d4e45347b6f
Revises: 2dacce02d64f
Create Date: 2026-05-11 00:09:24.375995+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "7d4e45347b6f"
down_revision: str | None = "2dacce02d64f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboards",
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{\"widgets\": []}'::jsonb"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dashboards_deleted_at"), "dashboards", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_dashboards_user_id"), "dashboards", ["user_id"], unique=True)
    op.drop_index(
        op.f("ix_addresses_trgm"),
        table_name="addresses",
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("addresses", "search_trgm")
    op.drop_index(
        op.f("ix_clients_trgm"),
        table_name="clients",
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("clients", "search_trgm")
    op.drop_index(op.f("ix_invoices_search_vector"), table_name="invoices", postgresql_using="gin")
    op.drop_index(
        op.f("ix_invoices_trgm"),
        table_name="invoices",
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("invoices", "search_vector")
    op.drop_column("invoices", "search_trgm")
    op.drop_index(
        op.f("ix_manufacturers_trgm"),
        table_name="manufacturers",
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("manufacturers", "search_trgm")
    op.drop_index(op.f("ix_parts_search_vector"), table_name="parts", postgresql_using="gin")
    op.drop_index(
        op.f("ix_parts_trgm"),
        table_name="parts",
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("parts", "search_vector")
    op.drop_column("parts", "search_trgm")
    op.drop_index(op.f("ix_reports_search_vector"), table_name="reports", postgresql_using="gin")
    op.drop_index(
        op.f("ix_reports_trgm"),
        table_name="reports",
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("reports", "search_vector")
    op.drop_column("reports", "search_trgm")
    op.drop_index(
        op.f("ix_survey_templates_trgm"),
        table_name="survey_templates",
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("survey_templates", "search_trgm")
    op.drop_index(
        op.f("ix_users_trgm"),
        table_name="users",
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("users", "search_trgm")
    op.drop_index(
        op.f("ix_vessels_trgm"),
        table_name="vessels",
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("vessels", "search_trgm")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vessels",
        sa.Column(
            "search_trgm",
            sa.TEXT(),
            sa.Computed(
                "((((COALESCE(name, ''::text) || ' '::text) || COALESCE(hin, ''::text)) || ' '::text) || COALESCE(model, ''::text))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_vessels_trgm"),
        "vessels",
        ["search_trgm"],
        unique=False,
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.add_column(
        "users",
        sa.Column(
            "search_trgm",
            sa.TEXT(),
            sa.Computed("((COALESCE(name, ''::text) || ' '::text) || COALESCE(email, ''::text))", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_users_trgm"),
        "users",
        ["search_trgm"],
        unique=False,
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.add_column(
        "survey_templates",
        sa.Column(
            "search_trgm",
            sa.TEXT(),
            sa.Computed("COALESCE(name, ''::text)", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_survey_templates_trgm"),
        "survey_templates",
        ["search_trgm"],
        unique=False,
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.add_column(
        "reports",
        sa.Column(
            "search_trgm",
            sa.TEXT(),
            sa.Computed("COALESCE(title, ''::text)", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "reports",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english'::regconfig, COALESCE(summary, ''::text))", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_reports_trgm"),
        "reports",
        ["search_trgm"],
        unique=False,
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_reports_search_vector"), "reports", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.add_column(
        "parts",
        sa.Column(
            "search_trgm",
            sa.TEXT(),
            sa.Computed("((COALESCE(name, ''::text) || ' '::text) || COALESCE(part_number, ''::text))", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "parts",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english'::regconfig, COALESCE(description, ''::text))", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_parts_trgm"),
        "parts",
        ["search_trgm"],
        unique=False,
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_parts_search_vector"), "parts", ["search_vector"], unique=False, postgresql_using="gin")
    op.add_column(
        "manufacturers",
        sa.Column(
            "search_trgm",
            sa.TEXT(),
            sa.Computed("((COALESCE(name, ''::text) || ' '::text) || COALESCE(country, ''::text))", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_manufacturers_trgm"),
        "manufacturers",
        ["search_trgm"],
        unique=False,
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.add_column(
        "invoices",
        sa.Column(
            "search_trgm",
            sa.TEXT(),
            sa.Computed("COALESCE(invoice_number, ''::text)", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "invoices",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english'::regconfig, COALESCE(notes, ''::text))", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_invoices_trgm"),
        "invoices",
        ["search_trgm"],
        unique=False,
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_invoices_search_vector"), "invoices", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.add_column(
        "clients",
        sa.Column(
            "search_trgm",
            sa.TEXT(),
            sa.Computed(
                "((((((((COALESCE(display_name, ''::text) || ' '::text) || COALESCE(email, ''::text)) || ' '::text) || COALESCE(first_name, ''::text)) || ' '::text) || COALESCE(last_name, ''::text)) || ' '::text) || COALESCE(company_name, ''::text))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_clients_trgm"),
        "clients",
        ["search_trgm"],
        unique=False,
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.add_column(
        "addresses",
        sa.Column(
            "search_trgm",
            sa.TEXT(),
            sa.Computed(
                "((((((COALESCE(line1, ''::text) || ' '::text) || COALESCE(city, ''::text)) || ' '::text) || COALESCE(region, ''::text)) || ' '::text) || COALESCE(postal_code, ''::text))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_addresses_trgm"),
        "addresses",
        ["search_trgm"],
        unique=False,
        postgresql_ops={"search_trgm": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_dashboards_user_id"), table_name="dashboards")
    op.drop_index(op.f("ix_dashboards_deleted_at"), table_name="dashboards")
    op.drop_table("dashboards")
    # ### end Alembic commands ###
