"""add_business_sequences

Revision ID: 4375807e51f7
Revises: 1de00d935b89
Create Date: 2026-05-12 03:44:19.793552+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op
from app.platform.sequences.enums import SequenceType
from app.utils.sqids import SqidType
from app.utils.textenum import TextEnum

# revision identifiers, used by Alembic.
revision: str = "4375807e51f7"
down_revision: str | None = "1de00d935b89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_sequences",
        sa.Column("type", TextEnum(SequenceType), nullable=False),
        sa.Column("current_value", sa.BigInteger(), nullable=False),
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "type", name="uq_business_sequences_org_type"),
    )
    op.create_index(op.f("ix_business_sequences_deleted_at"), "business_sequences", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_business_sequences_organization_id"), "business_sequences", ["organization_id"], unique=False
    )
    op.add_column("invoices", sa.Column("identifier", sa.Text(), nullable=True))
    op.drop_index(op.f("ix_invoices_survey_id"), table_name="invoices")
    op.create_index(op.f("ix_invoices_survey_id"), "invoices", ["survey_id"], unique=False)
    op.drop_column("invoices", "invoice_number")
    op.add_column("quotes", sa.Column("identifier", sa.Text(), nullable=True))
    op.drop_index(op.f("ix_quotes_survey_id"), table_name="quotes")
    op.create_index(op.f("ix_quotes_survey_id"), "quotes", ["survey_id"], unique=False)
    op.add_column("reports", sa.Column("identifier", sa.Text(), nullable=True))
    op.add_column("surveys", sa.Column("identifier", sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Rebuild search_trgm computed columns whose source columns changed,
    # and add search_trgm to tables that newly gained a SearchMixin.
    _rebuild_search_trgm("invoices", "coalesce(identifier, '')")
    _rebuild_search_trgm("reports", "coalesce(identifier, '') || ' ' || coalesce(title, '')")
    _add_search_trgm("quotes", "coalesce(identifier, '')")
    _add_search_trgm("surveys", "coalesce(identifier, '')")


def _drop_trgm_index_and_column(table: str) -> None:
    op.execute(f"DROP INDEX IF EXISTS ix_{table}_trgm")
    op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS search_trgm")


def _create_trgm_column_and_index(table: str, expression: str) -> None:
    op.execute(f"ALTER TABLE {table} ADD COLUMN search_trgm TEXT GENERATED ALWAYS AS ({expression}) STORED")
    op.execute(f"CREATE INDEX ix_{table}_trgm ON {table} USING GIN (search_trgm gin_trgm_ops)")


def _rebuild_search_trgm(table: str, expression: str) -> None:
    _drop_trgm_index_and_column(table)
    _create_trgm_column_and_index(table, expression)


def _add_search_trgm(table: str, expression: str) -> None:
    _create_trgm_column_and_index(table, expression)


def downgrade() -> None:
    _drop_trgm_index_and_column("surveys")
    _drop_trgm_index_and_column("quotes")
    _drop_trgm_index_and_column("reports")
    _create_trgm_column_and_index("reports", "coalesce(title, '')")
    _drop_trgm_index_and_column("invoices")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveys", "identifier")
    op.drop_column("reports", "identifier")
    op.drop_index(op.f("ix_quotes_survey_id"), table_name="quotes")
    op.create_index(op.f("ix_quotes_survey_id"), "quotes", ["survey_id"], unique=True)
    op.drop_column("quotes", "identifier")
    op.add_column("invoices", sa.Column("invoice_number", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_invoices_survey_id"), table_name="invoices")
    op.create_index(op.f("ix_invoices_survey_id"), "invoices", ["survey_id"], unique=True)
    op.drop_column("invoices", "identifier")
    op.drop_index(op.f("ix_business_sequences_organization_id"), table_name="business_sequences")
    op.drop_index(op.f("ix_business_sequences_deleted_at"), table_name="business_sequences")
    op.drop_table("business_sequences")
    # ### end Alembic commands ###
    _create_trgm_column_and_index("invoices", "coalesce(invoice_number, '')")
