"""add_pricing_guides_quotes_client_user_id

Revision ID: 90a6a327cfbe
Revises: a1b2c3d4e5f6
Create Date: 2026-05-10 05:23:30.289042+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op
from app.domain.pricing_guides.enums import PricingType
from app.domain.quotes.enums import QuoteState
from app.utils.sqids import SqidType
from app.utils.textenum import TextEnum

# revision identifiers, used by Alembic.
revision: str = "90a6a327cfbe"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_guides",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pricing_guides_deleted_at"), "pricing_guides", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_pricing_guides_organization_id"), "pricing_guides", ["organization_id"], unique=False)
    op.create_index(op.f("ix_pricing_guides_user_id"), "pricing_guides", ["user_id"], unique=False)
    op.create_table(
        "pricing_tiers",
        sa.Column("guide_id", SqidType(), nullable=False),
        sa.Column("service_type", sa.Text(), nullable=True),
        sa.Column("length_min_ft", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("length_max_ft", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("pricing_type", TextEnum(PricingType), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["guide_id"], ["pricing_guides.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pricing_tiers_guide_id"), "pricing_tiers", ["guide_id"], unique=False)
    op.create_table(
        "quotes",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("survey_id", SqidType(), nullable=False),
        sa.Column("client_id", SqidType(), nullable=False),
        sa.Column("pricing_guide_id", SqidType(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", TextEnum(QuoteState), server_default="draft", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["pricing_guide_id"], ["pricing_guides.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quotes_client_id"), "quotes", ["client_id"], unique=False)
    op.create_index(op.f("ix_quotes_deleted_at"), "quotes", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_quotes_organization_id"), "quotes", ["organization_id"], unique=False)
    op.create_index(op.f("ix_quotes_pricing_guide_id"), "quotes", ["pricing_guide_id"], unique=False)
    op.create_index(op.f("ix_quotes_state"), "quotes", ["state"], unique=False)
    op.create_index(op.f("ix_quotes_survey_id"), "quotes", ["survey_id"], unique=False)
    op.create_table(
        "quote_line_items",
        sa.Column("quote_id", SqidType(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["quote_id"], ["quotes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quote_line_items_quote_id"), "quote_line_items", ["quote_id"], unique=False)
    op.add_column("clients", sa.Column("user_id", SqidType(), nullable=True))
    op.create_index(op.f("ix_clients_user_id"), "clients", ["user_id"], unique=False)
    op.create_foreign_key("clients_user_id_fkey", "clients", "users", ["user_id"], ["id"], ondelete="SET NULL")


def downgrade() -> None:
    op.drop_constraint("clients_user_id_fkey", "clients", type_="foreignkey")
    op.drop_index(op.f("ix_clients_user_id"), table_name="clients")
    op.drop_column("clients", "user_id")
    op.drop_index(op.f("ix_quote_line_items_quote_id"), table_name="quote_line_items")
    op.drop_table("quote_line_items")
    op.drop_index(op.f("ix_quotes_survey_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_state"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_pricing_guide_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_organization_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_deleted_at"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_client_id"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_index(op.f("ix_pricing_tiers_guide_id"), table_name="pricing_tiers")
    op.drop_table("pricing_tiers")
    op.drop_index(op.f("ix_pricing_guides_user_id"), table_name="pricing_guides")
    op.drop_index(op.f("ix_pricing_guides_organization_id"), table_name="pricing_guides")
    op.drop_index(op.f("ix_pricing_guides_deleted_at"), table_name="pricing_guides")
    op.drop_table("pricing_guides")
