"""add all domain models

Revision ID: e229da637a4b
Revises: 0000000000000
Create Date: 2026-05-08 02:22:32.083113+00:00

"""

from enum import Enum as _Enum
from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.domain.clients.enums import ClientType
from app.domain.invoices.enums import InvoiceState
from app.domain.reports.enums import ReportState
from app.domain.subscriptions.enums import SubscriptionPlan, SubscriptionStatus
from app.domain.surveys.enums import SurveyState


class FindingSeverity(_Enum):
    A_safety_critical = "A_safety_critical"
    B_significant = "B_significant"
    C_minor = "C_minor"


class RecommendationTimeframe(_Enum):
    immediate = "immediate"
    within_30_days = "within_30_days"
    within_60_days = "within_60_days"
    within_90_days = "within_90_days"
    prior_to_next_haulout = "prior_to_next_haulout"
    monitor_only = "monitor_only"
    informational = "informational"


class SurveyPartyRole(_Enum):
    engaging_party = "engaging_party"
    buyer = "buyer"
    seller = "seller"
    current_owner = "current_owner"
    insurer = "insurer"
    lender = "lender"
    broker = "broker"
    attorney = "attorney"
    other = "other"


# Inline definitions for enums deleted in a later migration — kept here so
# this migration file remains replayable from scratch.
class AppraisalPurpose(_Enum):
    insurance = "insurance"
    sale = "sale"
    estate = "estate"
    donation = "donation"
    financing = "financing"
    other = "other"


class LossType(_Enum):
    grounding = "grounding"
    collision = "collision"
    fire = "fire"
    flooding = "flooding"
    storm = "storm"
    theft = "theft"
    vandalism = "vandalism"
    other = "other"


class ResponseItemStatus(_Enum):
    not_started = "not_started"
    in_progress = "in_progress"
    complete = "complete"
    not_applicable = "not_applicable"


class SurveyType(_Enum):
    pre_purchase = "pre_purchase"
    condition_and_valuation = "condition_and_valuation"
    damage = "damage"
    appraisal = "appraisal"


class SystemArea(_Enum):
    hull = "hull"
    deck = "deck"
    rigging = "rigging"
    propulsion = "propulsion"
    fuel = "fuel"
    electrical_ac = "electrical_ac"
    electrical_dc = "electrical_dc"
    plumbing = "plumbing"
    safety = "safety"
    electronics = "electronics"
    interior = "interior"
    cosmetic = "cosmetic"
    other = "other"


class VesselStateAtInspection(_Enum):
    afloat = "afloat"
    on_hard = "on_hard"
    on_trailer = "on_trailer"
    in_lift = "in_lift"


from app.domain.users.roles import Role  # noqa: E402
from app.domain.vessels.enums import (  # noqa: E402
    EnginePosition,
    EngineType,
    FuelType,
    HullMaterial,
    PropulsionType,
    RiggingType,
    VesselType,
)


# EmailMessageStatus is defined inline (was deleted in a later migration that
# collapsed email_messages + inbound_emails into a unified `messages` table).
class EmailMessageStatus(_Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"


from app.platform.documents.enums import DocumentStates  # noqa: E402
from app.platform.events.enums import EventType  # noqa: E402
from app.platform.llm.enums import MessageRole  # noqa: E402
from app.platform.media.enums import MediaStates  # noqa: E402
from app.platform.queue.enums import TaskStatus  # noqa: E402
from app.utils.sqids import SqidType  # noqa: E402
from app.utils.textenum import TextEnum  # noqa: E402

# revision identifiers, used by Alembic.
revision: str = "e229da637a4b"
down_revision: str | None = "0000000000000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("line1", sa.Text(), nullable=False),
        sa.Column("line2", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("region", sa.Text(), nullable=False),
        sa.Column("postal_code", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), server_default="US", nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("file_key", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_type", sa.Text(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("thumbnail_key", sa.Text(), nullable=True),
        sa.Column("state", TextEnum(DocumentStates), server_default="PENDING", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_key"),
    )
    op.create_index(op.f("ix_documents_state"), "documents", ["state"], unique=False)
    op.create_table(
        "email_threads",
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("participant_email", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_threads_participant_email"), "email_threads", ["participant_email"], unique=False)
    op.create_table(
        "event_consumer_failures",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("consumer_key", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_consumer_failures_consumer_key"), "event_consumer_failures", ["consumer_key"], unique=False
    )
    op.create_index(op.f("ix_event_consumer_failures_event_id"), "event_consumer_failures", ["event_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("event_type", TextEnum(EventType), nullable=False),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_actor_id"), "events", ["actor_id"], unique=False)
    op.create_index("ix_events_object", "events", ["object_type", "object_id", "created_at"], unique=False)
    op.create_index("ix_events_org_created", "events", ["organization_id", "created_at"], unique=False)
    op.create_index(op.f("ix_events_organization_id"), "events", ["organization_id"], unique=False)
    op.create_table(
        "llm_threads",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("threadable_type", sa.Text(), nullable=True),
        sa.Column("threadable_id", sa.Integer(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_threads_threadable_id"), "llm_threads", ["threadable_id"], unique=False)
    op.create_index(op.f("ix_llm_threads_threadable_type"), "llm_threads", ["threadable_type"], unique=False)
    op.create_index(op.f("ix_llm_threads_user_id"), "llm_threads", ["user_id"], unique=False)
    op.create_table(
        "media",
        sa.Column("file_key", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_type", sa.Text(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("thumbnail_key", sa.Text(), nullable=True),
        sa.Column("state", TextEnum(MediaStates), server_default="PENDING", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_key"),
    )
    op.create_index(op.f("ix_media_state"), "media", ["state"], unique=False)
    op.create_table(
        "state_transition_logs",
        sa.Column("object_type", sa.String(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("from_state", sa.String(), nullable=False),
        sa.Column("to_state", sa.String(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_stl_object_lookup", "state_transition_logs", ["object_type", "object_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("job_key", sa.Text(), nullable=False),
        sa.Column("queue", sa.Text(), nullable=False),
        sa.Column("task_name", sa.Text(), nullable=False),
        sa.Column("status", TextEnum(TaskStatus), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_job_key"), "tasks", ["job_key"], unique=True)
    op.create_index(op.f("ix_tasks_task_name"), "tasks", ["task_name"], unique=False)
    op.create_table(
        "threads",
        sa.Column("threadable_type", sa.Text(), nullable=False),
        sa.Column("threadable_id", sa.Integer(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("threadable_type", "threadable_id", name="uq_thread_per_object"),
    )
    op.create_index(op.f("ix_threads_threadable_id"), "threads", ["threadable_id"], unique=False)
    op.create_index(op.f("ix_threads_threadable_type"), "threads", ["threadable_type"], unique=False)
    op.create_table(
        "email_messages",
        sa.Column("to_email", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("from_email", sa.Text(), nullable=False),
        sa.Column("from_name", sa.Text(), nullable=True),
        sa.Column("reply_to_email", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("ses_message_id", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", TextEnum(EmailMessageStatus), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("email_thread_id", SqidType(), nullable=True),
        sa.Column("in_reply_to_message_id", sa.Text(), nullable=True),
        sa.Column("message_id", sa.Text(), nullable=True),
        sa.Column("template_name", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["email_thread_id"], ["email_threads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ses_message_id"),
    )
    op.create_index(op.f("ix_email_messages_email_thread_id"), "email_messages", ["email_thread_id"], unique=False)
    op.create_index(op.f("ix_email_messages_message_id"), "email_messages", ["message_id"], unique=True)
    op.create_table(
        "inbound_emails",
        sa.Column("s3_bucket", sa.Text(), nullable=False),
        sa.Column("s3_key", sa.Text(), nullable=False),
        sa.Column("ses_message_id", sa.Text(), nullable=True),
        sa.Column("from_email", sa.Text(), nullable=True),
        sa.Column("to_email", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("in_reply_to", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("email_thread_id", SqidType(), nullable=True),
        sa.Column("attachments_json", sa.JSON(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["email_thread_id"], ["email_threads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inbound_emails_email_thread_id"), "inbound_emails", ["email_thread_id"], unique=False)
    op.create_index(op.f("ix_inbound_emails_s3_key"), "inbound_emails", ["s3_key"], unique=True)
    op.create_index(op.f("ix_inbound_emails_ses_message_id"), "inbound_emails", ["ses_message_id"], unique=True)
    op.create_table(
        "llm_messages",
        sa.Column("thread_id", SqidType(), nullable=False),
        sa.Column("role", TextEnum(MessageRole), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["llm_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_messages_thread_id"), "llm_messages", ["thread_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("thread_id", SqidType(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_messages_thread_created", "messages", ["thread_id", "created_at"], unique=False)
    op.create_index(op.f("ix_messages_thread_id"), "messages", ["thread_id"], unique=False)
    op.create_index(op.f("ix_messages_user_id"), "messages", ["user_id"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("address_id", SqidType(), nullable=True),
        sa.Column("nams_member_number", sa.Text(), nullable=True),
        sa.Column("sams_member_number", sa.Text(), nullable=True),
        sa.Column("signature_block", sa.Text(), nullable=True),
        sa.Column("report_footer", sa.Text(), nullable=True),
        sa.Column("stripe_account_id", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["address_id"], ["addresses.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_address_id"), "organizations", ["address_id"], unique=False)
    op.create_table(
        "thread_read_statuses",
        sa.Column("thread_id", SqidType(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_thread_read_status_lookup", "thread_read_statuses", ["thread_id", "user_id", "read_at"], unique=False
    )
    op.create_index(op.f("ix_thread_read_statuses_thread_id"), "thread_read_statuses", ["thread_id"], unique=False)
    op.create_index(op.f("ix_thread_read_statuses_user_id"), "thread_read_statuses", ["user_id"], unique=False)
    op.create_table(
        "clients",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("client_type", TextEnum(ClientType), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("billing_address_id", SqidType(), nullable=True),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("company_name", sa.Text(), nullable=True),
        sa.Column("claim_contact_name", sa.Text(), nullable=True),
        sa.Column("institution_name", sa.Text(), nullable=True),
        sa.Column("loan_officer_name", sa.Text(), nullable=True),
        sa.Column("brokerage_name", sa.Text(), nullable=True),
        sa.Column("agent_name", sa.Text(), nullable=True),
        sa.Column("license_number", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["billing_address_id"], ["addresses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_billing_address_id"), "clients", ["billing_address_id"], unique=False)
    op.create_index(op.f("ix_clients_client_type"), "clients", ["client_type"], unique=False)
    op.create_index(op.f("ix_clients_deleted_at"), "clients", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_clients_organization_id"), "clients", ["organization_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("plan", TextEnum(SubscriptionPlan), nullable=False),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stripe_customer_id", sa.Text(), nullable=True),
        sa.Column("stripe_subscription_id", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", TextEnum(SubscriptionStatus), server_default="trialing", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", name="uq_subscription_per_org"),
    )
    op.create_index(op.f("ix_subscriptions_deleted_at"), "subscriptions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_subscriptions_organization_id"), "subscriptions", ["organization_id"], unique=False)
    op.create_index(op.f("ix_subscriptions_state"), "subscriptions", ["state"], unique=False)
    op.create_table(
        "survey_templates",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("applies_to_survey_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("definition_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_survey_templates_deleted_at"), "survey_templates", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_survey_templates_organization_id"), "survey_templates", ["organization_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("role", TextEnum(Role), server_default="MEMBER", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "vessels",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("hin", sa.Text(), nullable=True),
        sa.Column("uscg_official_number", sa.Text(), nullable=True),
        sa.Column("state_registration_number", sa.Text(), nullable=True),
        sa.Column("builder", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("vessel_type", TextEnum(VesselType), nullable=True),
        sa.Column("propulsion_type", TextEnum(PropulsionType), nullable=True),
        sa.Column("rigging_type", TextEnum(RiggingType), nullable=True),
        sa.Column("loa_ft", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("beam_ft", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("draft_ft", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("displacement_lbs", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("fuel_capacity_gal", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("hull_material", TextEnum(HullMaterial), nullable=True),
        sa.Column("construction_notes", sa.Text(), nullable=True),
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("home_port_address_id", SqidType(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["home_port_address_id"], ["addresses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vessels_deleted_at"), "vessels", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_vessels_hin"), "vessels", ["hin"], unique=False)
    op.create_index(op.f("ix_vessels_home_port_address_id"), "vessels", ["home_port_address_id"], unique=False)
    op.create_index(op.f("ix_vessels_organization_id"), "vessels", ["organization_id"], unique=False)
    op.create_table(
        "engines",
        sa.Column("vessel_id", SqidType(), nullable=False),
        sa.Column("position", TextEnum(EnginePosition), nullable=False),
        sa.Column("make", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("serial_number", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("horsepower", sa.Integer(), nullable=True),
        sa.Column("fuel_type", TextEnum(FuelType), nullable=True),
        sa.Column("engine_type", TextEnum(EngineType), nullable=True),
        sa.Column("hours_at_survey", sa.Integer(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vessel_id"], ["vessels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_engines_vessel_id"), "engines", ["vessel_id"], unique=False)
    op.create_table(
        "magic_link_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_magic_link_tokens_token_hash"), "magic_link_tokens", ["token_hash"], unique=True)
    op.create_index(op.f("ix_magic_link_tokens_user_id"), "magic_link_tokens", ["user_id"], unique=False)
    op.create_table(
        "surveys",
        sa.Column("survey_type", TextEnum(SurveyType), nullable=False),
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("vessel_id", SqidType(), nullable=False),
        sa.Column("assigned_surveyor_id", SqidType(), nullable=False),
        sa.Column("template_id", SqidType(), nullable=True),
        sa.Column("inspection_location_address_id", SqidType(), nullable=True),
        sa.Column("vessel_state_at_inspection", TextEnum(VesselStateAtInspection), nullable=True),
        sa.Column("weather_conditions", sa.Text(), nullable=True),
        sa.Column("purpose_statement", sa.Text(), nullable=True),
        sa.Column("scope_statement", sa.Text(), nullable=True),
        sa.Column("exclusions", sa.Text(), nullable=True),
        sa.Column("limitations", sa.Text(), nullable=True),
        sa.Column("quoted_fee_cents", sa.Integer(), nullable=True),
        sa.Column("included_sea_trial", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("included_haul_out", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inspection_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inspection_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purchase_price_cents", sa.Integer(), nullable=True),
        sa.Column("seller_name", sa.Text(), nullable=True),
        sa.Column("policy_number", sa.Text(), nullable=True),
        sa.Column("renewal_required_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column("incident_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("incident_description", sa.Text(), nullable=True),
        sa.Column("loss_type", TextEnum(LossType), nullable=True),
        sa.Column("claim_number", sa.Text(), nullable=True),
        sa.Column("pending_insurer_approval", sa.Boolean(), nullable=True),
        sa.Column("appraisal_purpose", TextEnum(AppraisalPurpose), nullable=True),
        sa.Column("effective_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", TextEnum(SurveyState), server_default="inquiry", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["assigned_surveyor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["inspection_location_address_id"], ["addresses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["template_id"], ["survey_templates.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vessel_id"], ["vessels.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_surveys_assigned_surveyor_id"), "surveys", ["assigned_surveyor_id"], unique=False)
    op.create_index(op.f("ix_surveys_deleted_at"), "surveys", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_surveys_inspection_location_address_id"), "surveys", ["inspection_location_address_id"], unique=False
    )
    op.create_index(op.f("ix_surveys_organization_id"), "surveys", ["organization_id"], unique=False)
    op.create_index(op.f("ix_surveys_state"), "surveys", ["state"], unique=False)
    op.create_index(op.f("ix_surveys_survey_type"), "surveys", ["survey_type"], unique=False)
    op.create_index(op.f("ix_surveys_template_id"), "surveys", ["template_id"], unique=False)
    op.create_index(op.f("ix_surveys_vessel_id"), "surveys", ["vessel_id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("survey_id", SqidType(), nullable=False),
        sa.Column("client_id", SqidType(), nullable=False),
        sa.Column("invoice_number", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("currency", sa.Text(), server_default="USD", nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tax_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("payment_link_url", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", TextEnum(InvoiceState), server_default="draft", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_client_id"), "invoices", ["client_id"], unique=False)
    op.create_index(op.f("ix_invoices_deleted_at"), "invoices", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_invoices_organization_id"), "invoices", ["organization_id"], unique=False)
    op.create_index(op.f("ix_invoices_state"), "invoices", ["state"], unique=False)
    op.create_index(op.f("ix_invoices_survey_id"), "invoices", ["survey_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("survey_id", SqidType(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("market_value_cents", sa.Integer(), nullable=True),
        sa.Column("replacement_value_cents", sa.Integer(), nullable=True),
        sa.Column("watermarked_file_key", sa.Text(), nullable=True),
        sa.Column("released_file_key", sa.Text(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", TextEnum(ReportState), server_default="draft", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_deleted_at"), "reports", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_reports_organization_id"), "reports", ["organization_id"], unique=False)
    op.create_index(op.f("ix_reports_state"), "reports", ["state"], unique=False)
    op.create_index(op.f("ix_reports_survey_id"), "reports", ["survey_id"], unique=False)
    op.create_table(
        "survey_parties",
        sa.Column("survey_id", SqidType(), nullable=False),
        sa.Column("client_id", SqidType(), nullable=False),
        sa.Column("role", TextEnum(SurveyPartyRole), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("survey_id", "client_id", "role", name="uq_survey_party"),
    )
    op.create_index(op.f("ix_survey_parties_client_id"), "survey_parties", ["client_id"], unique=False)
    op.create_index(op.f("ix_survey_parties_survey_id"), "survey_parties", ["survey_id"], unique=False)
    op.create_table(
        "survey_response_items",
        sa.Column("survey_id", SqidType(), nullable=False),
        sa.Column("template_node_ref", sa.Text(), nullable=True),
        sa.Column("heading_label", sa.Text(), nullable=False),
        sa.Column("category_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("status", TextEnum(ResponseItemStatus), server_default="not_started", nullable=False),
        sa.Column("is_finding", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_survey_response_items_survey_id"), "survey_response_items", ["survey_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("survey_id", SqidType(), nullable=False),
        sa.Column("response_item_id", SqidType(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("system_area", TextEnum(SystemArea), nullable=True),
        sa.Column("severity", TextEnum(FindingSeverity), nullable=True),
        sa.Column("location_on_vessel", sa.Text(), nullable=True),
        sa.Column("is_pre_existing", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["response_item_id"], ["survey_response_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_response_item_id"), "findings", ["response_item_id"], unique=False)
    op.create_index(op.f("ix_findings_survey_id"), "findings", ["survey_id"], unique=False)
    op.create_table(
        "invoice_line_items",
        sa.Column("invoice_id", SqidType(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_line_items_invoice_id"), "invoice_line_items", ["invoice_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("finding_id", SqidType(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("timeframe", TextEnum(RecommendationTimeframe), nullable=False),
        sa.Column("is_completed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recommendations_finding_id"), "recommendations", ["finding_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendations_finding_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_invoice_line_items_invoice_id"), table_name="invoice_line_items")
    op.drop_table("invoice_line_items")
    op.drop_index(op.f("ix_findings_survey_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_response_item_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_survey_response_items_survey_id"), table_name="survey_response_items")
    op.drop_table("survey_response_items")
    op.drop_index(op.f("ix_survey_parties_survey_id"), table_name="survey_parties")
    op.drop_index(op.f("ix_survey_parties_client_id"), table_name="survey_parties")
    op.drop_table("survey_parties")
    op.drop_index(op.f("ix_reports_survey_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_state"), table_name="reports")
    op.drop_index(op.f("ix_reports_organization_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_deleted_at"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_invoices_survey_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_state"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_organization_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_deleted_at"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_client_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_surveys_vessel_id"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_template_id"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_survey_type"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_state"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_organization_id"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_inspection_location_address_id"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_deleted_at"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_assigned_surveyor_id"), table_name="surveys")
    op.drop_table("surveys")
    op.drop_index(op.f("ix_magic_link_tokens_user_id"), table_name="magic_link_tokens")
    op.drop_index(op.f("ix_magic_link_tokens_token_hash"), table_name="magic_link_tokens")
    op.drop_table("magic_link_tokens")
    op.drop_index(op.f("ix_engines_vessel_id"), table_name="engines")
    op.drop_table("engines")
    op.drop_index(op.f("ix_vessels_organization_id"), table_name="vessels")
    op.drop_index(op.f("ix_vessels_home_port_address_id"), table_name="vessels")
    op.drop_index(op.f("ix_vessels_hin"), table_name="vessels")
    op.drop_index(op.f("ix_vessels_deleted_at"), table_name="vessels")
    op.drop_table("vessels")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_survey_templates_organization_id"), table_name="survey_templates")
    op.drop_index(op.f("ix_survey_templates_deleted_at"), table_name="survey_templates")
    op.drop_table("survey_templates")
    op.drop_index(op.f("ix_subscriptions_state"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_organization_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_deleted_at"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_clients_organization_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_deleted_at"), table_name="clients")
    op.drop_index(op.f("ix_clients_client_type"), table_name="clients")
    op.drop_index(op.f("ix_clients_billing_address_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_thread_read_statuses_user_id"), table_name="thread_read_statuses")
    op.drop_index(op.f("ix_thread_read_statuses_thread_id"), table_name="thread_read_statuses")
    op.drop_index("ix_thread_read_status_lookup", table_name="thread_read_statuses")
    op.drop_table("thread_read_statuses")
    op.drop_index(op.f("ix_organizations_address_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_messages_user_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_thread_id"), table_name="messages")
    op.drop_index("ix_messages_thread_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_llm_messages_thread_id"), table_name="llm_messages")
    op.drop_table("llm_messages")
    op.drop_index(op.f("ix_inbound_emails_ses_message_id"), table_name="inbound_emails")
    op.drop_index(op.f("ix_inbound_emails_s3_key"), table_name="inbound_emails")
    op.drop_index(op.f("ix_inbound_emails_email_thread_id"), table_name="inbound_emails")
    op.drop_table("inbound_emails")
    op.drop_index(op.f("ix_email_messages_message_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_email_thread_id"), table_name="email_messages")
    op.drop_table("email_messages")
    op.drop_index(op.f("ix_threads_threadable_type"), table_name="threads")
    op.drop_index(op.f("ix_threads_threadable_id"), table_name="threads")
    op.drop_table("threads")
    op.drop_index(op.f("ix_tasks_task_name"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_job_key"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_stl_object_lookup", table_name="state_transition_logs")
    op.drop_table("state_transition_logs")
    op.drop_index(op.f("ix_media_state"), table_name="media")
    op.drop_table("media")
    op.drop_index(op.f("ix_llm_threads_user_id"), table_name="llm_threads")
    op.drop_index(op.f("ix_llm_threads_threadable_type"), table_name="llm_threads")
    op.drop_index(op.f("ix_llm_threads_threadable_id"), table_name="llm_threads")
    op.drop_table("llm_threads")
    op.drop_index(op.f("ix_events_organization_id"), table_name="events")
    op.drop_index("ix_events_org_created", table_name="events")
    op.drop_index("ix_events_object", table_name="events")
    op.drop_index(op.f("ix_events_actor_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_event_consumer_failures_event_id"), table_name="event_consumer_failures")
    op.drop_index(op.f("ix_event_consumer_failures_consumer_key"), table_name="event_consumer_failures")
    op.drop_table("event_consumer_failures")
    op.drop_index(op.f("ix_email_threads_participant_email"), table_name="email_threads")
    op.drop_table("email_threads")
    op.drop_index(op.f("ix_documents_state"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("addresses")
    # ### end Alembic commands ###
