"""pricing_guide_active_per_user_index

Revision ID: dc6827a4afd0
Revises: 4a1f9c2d3e8b
Create Date: 2026-05-25 15:17:46.459775+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc6827a4afd0"
down_revision: str | None = "4a1f9c2d3e8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_pricing_guides_active_per_user",
        "pricing_guides",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_active AND deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_pricing_guides_active_per_user",
        table_name="pricing_guides",
        postgresql_where=sa.text("is_active AND deleted_at IS NULL"),
    )
    # ### end Alembic commands ###
