"""add_stripe_client_secret_to_invoices

Revision ID: 031623e5f5e2
Revises: b4f2c8e91a3d
Create Date: 2026-05-12 01:38:12.523049+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "031623e5f5e2"
down_revision: str | None = "b4f2c8e91a3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("stripe_client_secret", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "stripe_client_secret")
    # ### end Alembic commands ###
