"""add_messages_deleted_at_index

Revision ID: 008bc2f63f25
Revises: 80aeb9313250
Create Date: 2026-05-11 03:18:17.807012+00:00

"""

from typing import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "008bc2f63f25"
down_revision: str | None = "80aeb9313250"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_messages_deleted_at"), "messages", ["deleted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_deleted_at"), table_name="messages")
    # ### end Alembic commands ###
