"""add_llm_tool_calls_table

Revision ID: d8a968b85ea7
Revises: 008bc2f63f25
Create Date: 2026-05-11 04:50:53.814853+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "d8a968b85ea7"
down_revision: str | None = "008bc2f63f25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_tool_calls",
        sa.Column("message_id", SqidType(), nullable=False),
        sa.Column("tool_use_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "input", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("is_error", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["llm_messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_tool_calls_deleted_at"), "llm_tool_calls", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_llm_tool_calls_message_id"), "llm_tool_calls", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_tool_calls_message_id"), table_name="llm_tool_calls")
    op.drop_index(op.f("ix_llm_tool_calls_deleted_at"), table_name="llm_tool_calls")
    op.drop_table("llm_tool_calls")
    # ### end Alembic commands ###
