"""add_search_vectors

Revision ID: 9ba7aed24094
Revises: 169814776707
Create Date: 2026-05-10 03:45:00.563243+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ba7aed24094"
down_revision: str | None = "169814776707"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(line1, '') || ' ' || coalesce(city, '') || ' ' || coalesce(region, '') || ' ' || coalesce(postal_code, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(display_name, '') || ' ' || coalesce(email, '') || ' ' || coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(company_name, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "invoices",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(invoice_number, '') || ' ' || coalesce(notes, ''))", persisted=True
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "manufacturers",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(country, ''))", persisted=True),
            nullable=True,
        ),
    )
    op.add_column(
        "parts",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(name, '') || ' ' || coalesce(part_number, '') || ' ' || coalesce(description, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "reports",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(summary, ''))", persisted=True),
            nullable=True,
        ),
    )
    op.add_column(
        "survey_templates",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(name, ''))", persisted=True),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(email, ''))", persisted=True),
            nullable=True,
        ),
    )
    op.add_column(
        "vessels",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(name, '') || ' ' || coalesce(hin, '') || ' ' || coalesce(model, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in (
        "vessels",
        "users",
        "survey_templates",
        "reports",
        "parts",
        "manufacturers",
        "invoices",
        "clients",
        "addresses",
    ):
        op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS search_vector")
