"""drop surveys form_response column

Revision ID: daebab87cd6b
Revises: 1be0b79fb4ab
Create Date: 2026-05-17 05:15:01.226475+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "daebab87cd6b"
down_revision: str | None = "1be0b79fb4ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveys", "form_response")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveys",
        sa.Column("form_response", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
