"""add reports blocks column

Revision ID: 43ae0538636b
Revises: daebab87cd6b
Create Date: 2026-05-17 05:37:12.799837+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43ae0538636b"
down_revision: str | None = "daebab87cd6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports",
        sa.Column(
            "blocks", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "blocks")
    # ### end Alembic commands ###
