"""add_deleted_at_to_all_tables

Revision ID: 80aeb9313250
Revises: 42b9f1d0a1b7
Create Date: 2026-05-11 03:09:11.128263+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from alembic_utils.pg_policy import PGPolicy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80aeb9313250"
down_revision: str | None = "42b9f1d0a1b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_widgets_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.widgets",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.user_id', true), '') IS NOT NULL\n            AND user_id = NULLIF(current_setting('app.user_id', true), '')::int)\n    )",
    )
    op.create_entity(public_widgets_user_scope_policy)

    op.add_column("addresses", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_addresses_deleted_at"), "addresses", ["deleted_at"], unique=False)
    op.add_column("documents", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_documents_deleted_at"), "documents", ["deleted_at"], unique=False)
    op.add_column("email_messages", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("email_messages_rfc_message_id_key"), "email_messages", type_="unique")
    op.drop_constraint(op.f("email_messages_ses_message_id_key"), "email_messages", type_="unique")
    op.create_index(op.f("ix_email_messages_deleted_at"), "email_messages", ["deleted_at"], unique=False)
    op.add_column("email_threads", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_email_threads_deleted_at"), "email_threads", ["deleted_at"], unique=False)
    op.add_column("engines", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_engines_deleted_at"), "engines", ["deleted_at"], unique=False)
    op.add_column("event_consumer_failures", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        op.f("ix_event_consumer_failures_deleted_at"), "event_consumer_failures", ["deleted_at"], unique=False
    )
    op.add_column("events", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_events_deleted_at"), "events", ["deleted_at"], unique=False)
    op.add_column("invoice_line_items", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_invoice_line_items_deleted_at"), "invoice_line_items", ["deleted_at"], unique=False)
    op.add_column("llm_messages", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_llm_messages_deleted_at"), "llm_messages", ["deleted_at"], unique=False)
    op.add_column("llm_threads", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_llm_threads_deleted_at"), "llm_threads", ["deleted_at"], unique=False)
    op.add_column("magic_link_tokens", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_magic_link_tokens_deleted_at"), "magic_link_tokens", ["deleted_at"], unique=False)
    op.add_column("media", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_media_deleted_at"), "media", ["deleted_at"], unique=False)
    op.add_column("organizations", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_organizations_deleted_at"), "organizations", ["deleted_at"], unique=False)
    op.add_column("pricing_tiers", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_pricing_tiers_deleted_at"), "pricing_tiers", ["deleted_at"], unique=False)
    op.add_column("quote_line_items", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_quote_line_items_deleted_at"), "quote_line_items", ["deleted_at"], unique=False)
    op.add_column("state_transition_logs", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_state_transition_logs_deleted_at"), "state_transition_logs", ["deleted_at"], unique=False)
    op.add_column("tasks", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_tasks_deleted_at"), "tasks", ["deleted_at"], unique=False)
    op.add_column("thread_read_statuses", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_thread_read_statuses_deleted_at"), "thread_read_statuses", ["deleted_at"], unique=False)
    op.add_column("threads", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_threads_deleted_at"), "threads", ["deleted_at"], unique=False)
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.enable_rls("public", "widgets")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.disable_rls("public", "widgets")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_column("users", "deleted_at")
    op.drop_index(op.f("ix_threads_deleted_at"), table_name="threads")
    op.drop_column("threads", "deleted_at")
    op.drop_index(op.f("ix_thread_read_statuses_deleted_at"), table_name="thread_read_statuses")
    op.drop_column("thread_read_statuses", "deleted_at")
    op.drop_index(op.f("ix_tasks_deleted_at"), table_name="tasks")
    op.drop_column("tasks", "deleted_at")
    op.drop_index(op.f("ix_state_transition_logs_deleted_at"), table_name="state_transition_logs")
    op.drop_column("state_transition_logs", "deleted_at")
    op.drop_index(op.f("ix_quote_line_items_deleted_at"), table_name="quote_line_items")
    op.drop_column("quote_line_items", "deleted_at")
    op.drop_index(op.f("ix_pricing_tiers_deleted_at"), table_name="pricing_tiers")
    op.drop_column("pricing_tiers", "deleted_at")
    op.drop_index(op.f("ix_organizations_deleted_at"), table_name="organizations")
    op.drop_column("organizations", "deleted_at")
    op.drop_index(op.f("ix_media_deleted_at"), table_name="media")
    op.drop_column("media", "deleted_at")
    op.drop_index(op.f("ix_magic_link_tokens_deleted_at"), table_name="magic_link_tokens")
    op.drop_column("magic_link_tokens", "deleted_at")
    op.drop_index(op.f("ix_llm_threads_deleted_at"), table_name="llm_threads")
    op.drop_column("llm_threads", "deleted_at")
    op.drop_index(op.f("ix_llm_messages_deleted_at"), table_name="llm_messages")
    op.drop_column("llm_messages", "deleted_at")
    op.drop_index(op.f("ix_invoice_line_items_deleted_at"), table_name="invoice_line_items")
    op.drop_column("invoice_line_items", "deleted_at")
    op.drop_index(op.f("ix_events_deleted_at"), table_name="events")
    op.drop_column("events", "deleted_at")
    op.drop_index(op.f("ix_event_consumer_failures_deleted_at"), table_name="event_consumer_failures")
    op.drop_column("event_consumer_failures", "deleted_at")
    op.drop_index(op.f("ix_engines_deleted_at"), table_name="engines")
    op.drop_column("engines", "deleted_at")
    op.drop_index(op.f("ix_email_threads_deleted_at"), table_name="email_threads")
    op.drop_column("email_threads", "deleted_at")
    op.drop_index(op.f("ix_email_messages_deleted_at"), table_name="email_messages")
    op.create_unique_constraint(
        op.f("email_messages_ses_message_id_key"),
        "email_messages",
        ["ses_message_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("email_messages_rfc_message_id_key"),
        "email_messages",
        ["rfc_message_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("email_messages", "deleted_at")
    op.drop_index(op.f("ix_documents_deleted_at"), table_name="documents")
    op.drop_column("documents", "deleted_at")
    op.drop_index(op.f("ix_addresses_deleted_at"), table_name="addresses")
    op.drop_column("addresses", "deleted_at")
    public_widgets_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.widgets",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.user_id', true), '') IS NOT NULL\n            AND user_id = NULLIF(current_setting('app.user_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_widgets_user_scope_policy)

    # ### end Alembic commands ###
