"""cascade_delete_pricing_guides_user

Revision ID: b00e1fd26fbe
Revises: dc6827a4afd0
Create Date: 2026-05-25 15:33:51.861095+00:00

"""

from typing import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b00e1fd26fbe"
down_revision: str | None = "dc6827a4afd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("pricing_guides_user_id_fkey"), "pricing_guides", type_="foreignkey")
    op.create_foreign_key(None, "pricing_guides", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pricing_guides", type_="foreignkey")
    op.create_foreign_key(
        op.f("pricing_guides_user_id_fkey"), "pricing_guides", "users", ["user_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###
