"""survey_media field_id to node_id

Revision ID: 1be0b79fb4ab
Revises: fcad2a5ecd5b
Create Date: 2026-05-17 05:06:55.899250+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "1be0b79fb4ab"
down_revision: str | None = "fcad2a5ecd5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("survey_media", sa.Column("node_id", SqidType(), nullable=True))
    op.create_index(op.f("ix_survey_media_node_id"), "survey_media", ["node_id"], unique=False)
    op.create_foreign_key(None, "survey_media", "form_nodes", ["node_id"], ["id"], ondelete="SET NULL")
    op.drop_column("survey_media", "field_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("survey_media", sa.Column("field_id", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "survey_media", type_="foreignkey")
    op.drop_index(op.f("ix_survey_media_node_id"), table_name="survey_media")
    op.drop_column("survey_media", "node_id")
    # ### end Alembic commands ###
