"""Add comms email tables

Revision ID: 7e279f9a5e2e
Revises: e159feb64f82
Create Date: 2026-05-05 06:38:32.654924+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e279f9a5e2e"
down_revision: str | None = "e159feb64f82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_threads",
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("participant_email", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_threads_participant_email"), "email_threads", ["participant_email"], unique=False)
    op.create_table(
        "email_messages",
        sa.Column("to_email", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("from_email", sa.Text(), nullable=False),
        sa.Column("from_name", sa.Text(), nullable=True),
        sa.Column("reply_to_email", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("ses_message_id", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Enum("PENDING", "SENT", "FAILED", name="emailmessagestatus"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("email_thread_id", sa.Integer(), nullable=True),
        sa.Column("in_reply_to_message_id", sa.Text(), nullable=True),
        sa.Column("message_id", sa.Text(), nullable=True),
        sa.Column("template_name", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["email_thread_id"], ["email_threads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ses_message_id"),
    )
    op.create_index(op.f("ix_email_messages_email_thread_id"), "email_messages", ["email_thread_id"], unique=False)
    op.create_index(op.f("ix_email_messages_message_id"), "email_messages", ["message_id"], unique=True)
    op.create_table(
        "inbound_emails",
        sa.Column("s3_bucket", sa.Text(), nullable=False),
        sa.Column("s3_key", sa.Text(), nullable=False),
        sa.Column("ses_message_id", sa.Text(), nullable=True),
        sa.Column("from_email", sa.Text(), nullable=True),
        sa.Column("to_email", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("in_reply_to", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("email_thread_id", sa.Integer(), nullable=True),
        sa.Column("attachments_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["email_thread_id"], ["email_threads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inbound_emails_email_thread_id"), "inbound_emails", ["email_thread_id"], unique=False)
    op.create_index(op.f("ix_inbound_emails_s3_key"), "inbound_emails", ["s3_key"], unique=True)
    op.create_index(op.f("ix_inbound_emails_ses_message_id"), "inbound_emails", ["ses_message_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inbound_emails_ses_message_id"), table_name="inbound_emails")
    op.drop_index(op.f("ix_inbound_emails_s3_key"), table_name="inbound_emails")
    op.drop_index(op.f("ix_inbound_emails_email_thread_id"), table_name="inbound_emails")
    op.drop_table("inbound_emails")
    op.drop_index(op.f("ix_email_messages_message_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_email_thread_id"), table_name="email_messages")
    op.drop_table("email_messages")
    op.drop_index(op.f("ix_email_threads_participant_email"), table_name="email_threads")
    op.drop_table("email_threads")
    # ### end Alembic commands ###
