"""drop_sort_order_from_pricing_tiers

Revision ID: 81e5919d2df6
Revises: 5a6763b9cf9b
Create Date: 2026-05-25 22:04:38.547878+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81e5919d2df6"
down_revision: str | None = "5a6763b9cf9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pricing_tiers", "sort_order")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pricing_tiers",
        sa.Column("sort_order", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
