"""enable_rls_on_org_tables

Revision ID: 6b45fd3c4997
Revises: 3747d6aa5dbc
Create Date: 2026-05-12 04:13:05.479636+00:00

"""

from typing import Sequence

from alembic_utils.pg_policy import PGPolicy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b45fd3c4997"
down_revision: str | None = "3747d6aa5dbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_clients_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.clients",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND clients.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_clients_org_scope_policy)

    public_manufacturers_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.manufacturers",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND manufacturers.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_manufacturers_org_scope_policy)

    public_vessels_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.vessels",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND vessels.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_vessels_org_scope_policy)

    public_invoices_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.invoices",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND invoices.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_invoices_org_scope_policy)

    public_quotes_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.quotes",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND quotes.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_quotes_org_scope_policy)

    public_subscriptions_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.subscriptions",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND subscriptions.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_subscriptions_org_scope_policy)

    public_pricing_guides_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.pricing_guides",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND pricing_guides.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_pricing_guides_org_scope_policy)

    public_parts_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.parts",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND parts.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_parts_org_scope_policy)

    public_survey_templates_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.survey_templates",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND survey_templates.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_survey_templates_org_scope_policy)

    public_surveys_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.surveys",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND surveys.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_surveys_org_scope_policy)

    public_payment_methods_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.payment_methods",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND payment_methods.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_payment_methods_org_scope_policy)

    public_reports_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.reports",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND reports.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_reports_org_scope_policy)

    op.enable_rls("public", "clients")
    op.enable_rls("public", "invoices")
    op.enable_rls("public", "manufacturers")
    op.enable_rls("public", "parts")
    op.enable_rls("public", "payment_methods")
    op.enable_rls("public", "pricing_guides")
    op.enable_rls("public", "quotes")
    op.enable_rls("public", "reports")
    op.enable_rls("public", "subscriptions")
    op.enable_rls("public", "survey_templates")
    op.enable_rls("public", "surveys")
    op.enable_rls("public", "vessels")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.disable_rls("public", "vessels")
    op.disable_rls("public", "surveys")
    op.disable_rls("public", "survey_templates")
    op.disable_rls("public", "subscriptions")
    op.disable_rls("public", "reports")
    op.disable_rls("public", "quotes")
    op.disable_rls("public", "pricing_guides")
    op.disable_rls("public", "payment_methods")
    op.disable_rls("public", "parts")
    op.disable_rls("public", "manufacturers")
    op.disable_rls("public", "invoices")
    op.disable_rls("public", "clients")
    public_reports_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.reports",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND reports.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_reports_org_scope_policy)

    public_payment_methods_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.payment_methods",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND payment_methods.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_payment_methods_org_scope_policy)

    public_surveys_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.surveys",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND surveys.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_surveys_org_scope_policy)

    public_survey_templates_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.survey_templates",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND survey_templates.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_survey_templates_org_scope_policy)

    public_parts_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.parts",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND parts.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_parts_org_scope_policy)

    public_pricing_guides_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.pricing_guides",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND pricing_guides.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_pricing_guides_org_scope_policy)

    public_subscriptions_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.subscriptions",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND subscriptions.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_subscriptions_org_scope_policy)

    public_quotes_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.quotes",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND quotes.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_quotes_org_scope_policy)

    public_invoices_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.invoices",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND invoices.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_invoices_org_scope_policy)

    public_vessels_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.vessels",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND vessels.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_vessels_org_scope_policy)

    public_manufacturers_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.manufacturers",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND manufacturers.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_manufacturers_org_scope_policy)

    public_clients_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.clients",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND clients.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_clients_org_scope_policy)

    # ### end Alembic commands ###
