"""sync up

Revision ID: 33e741d88d6f
Revises: 673dda0f8398
Create Date: 2026-05-14 02:20:07.680165+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "33e741d88d6f"
down_revision: str | None = "673dda0f8398"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("calendar_events", sa.Column("name", sa.Text(), nullable=True))
    op.add_column("calendar_events", sa.Column("address_id", SqidType(), nullable=True))
    op.create_index(op.f("ix_calendar_events_address_id"), "calendar_events", ["address_id"], unique=False)
    op.create_foreign_key(None, "calendar_events", "addresses", ["address_id"], ["id"], ondelete="SET NULL")
    op.drop_column("calendar_events", "location")
    op.create_index(
        "ix_invoices_org_identifier",
        "invoices",
        ["organization_id", "identifier"],
        unique=True,
        postgresql_where=sa.text("identifier IS NOT NULL"),
    )
    op.create_index(
        "ix_quotes_org_identifier",
        "quotes",
        ["organization_id", "identifier"],
        unique=True,
        postgresql_where=sa.text("identifier IS NOT NULL"),
    )
    op.create_index(
        "ix_reports_org_identifier",
        "reports",
        ["organization_id", "identifier"],
        unique=True,
        postgresql_where=sa.text("identifier IS NOT NULL"),
    )
    op.create_index(
        "ix_surveys_org_identifier",
        "surveys",
        ["organization_id", "identifier"],
        unique=True,
        postgresql_where=sa.text("identifier IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_surveys_org_identifier", table_name="surveys", postgresql_where=sa.text("identifier IS NOT NULL"))
    op.drop_index("ix_reports_org_identifier", table_name="reports", postgresql_where=sa.text("identifier IS NOT NULL"))
    op.drop_index("ix_quotes_org_identifier", table_name="quotes", postgresql_where=sa.text("identifier IS NOT NULL"))
    op.drop_index(
        "ix_invoices_org_identifier", table_name="invoices", postgresql_where=sa.text("identifier IS NOT NULL")
    )
    op.add_column("calendar_events", sa.Column("location", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "calendar_events", type_="foreignkey")
    op.drop_index(op.f("ix_calendar_events_address_id"), table_name="calendar_events")
    op.drop_column("calendar_events", "address_id")
    op.drop_column("calendar_events", "name")
    # ### end Alembic commands ###
