/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_Invoice operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { InvoiceListItem } from "@/openapi/litestarAPI.schemas";
import { InvoiceState } from "@/openapi/litestarAPI.schemas";

export const invoiceColumnDefs = createColumnBuilder<InvoiceListItem>()
  .text("identifier", { header: "Identifier", sortable: true })
  .status("state", { header: "State", filterable: true, options: Object.values(InvoiceState) })
  .datetime("issued_at", { header: "Issued", sortable: true, filterable: true, hideOnMobile: true })
  .datetime("due_at", { header: "Due", sortable: true, filterable: true, hideOnMobile: true })
  .number("total_cents", { header: "Total Cents", sortable: true })
  .datetime("created_at", { header: "Created", sortable: true, filterable: true, hideOnMobile: true })
  .build();

export const InvoiceSortableColumn = {
  created_at: 'created_at',
  due_at: 'due_at',
  identifier: 'identifier',
  issued_at: 'issued_at',
  total_cents: 'total_cents',
} as const;

export const InvoiceFilterableColumn = {
  client_id: 'client_id',
  created_at: 'created_at',
  due_at: 'due_at',
  issued_at: 'issued_at',
  state: 'state',
  survey_id: 'survey_id',
} as const;
