/**
 * Generated by generate-orval-operations.ts — DO NOT EDIT
 * Maps CRUD list operations (POST) to query hooks instead of mutations.
 */
export const crudOperations: Record<string, { query: { useQuery: boolean } }> = {
  list_CalendarEvent: { query: { useQuery: true } },
  list_Client: { query: { useQuery: true } },
  list_EmailThread: { query: { useQuery: true } },
  list_Message: { query: { useQuery: true } },
  list_Invoice: { query: { useQuery: true } },
  list_Manufacturer: { query: { useQuery: true } },
  list_Part: { query: { useQuery: true } },
  list_PaymentMethod: { query: { useQuery: true } },
  list_PricingGuide: { query: { useQuery: true } },
  list_Report: { query: { useQuery: true } },
  list_Subscription: { query: { useQuery: true } },
  list_Survey: { query: { useQuery: true } },
  list_SurveyTemplate: { query: { useQuery: true } },
  list_User: { query: { useQuery: true } },
  list_Vessel: { query: { useQuery: true } },
};
