/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * State-machine metadata per resource, sourced from backend StateMachineMixin.
 */
export interface StateMachineMeta {
  column: string;
  states: readonly string[];
  actionGroup: string | undefined;
}

export const RESOURCE_STATE_MACHINES: Record<string, StateMachineMeta> = {
  "calendar-events": { column: "state", states: ["tentative", "confirmed", "completed", "cancelled"], actionGroup: "calendar_event_actions" },
  "messages": { column: "state", states: ["received", "queued", "sent", "failed"], actionGroup: "message_actions" },
  "invoices": { column: "state", states: ["draft", "sent", "paid", "overdue", "void", "refunded"], actionGroup: "invoice_actions" },
  "reports": { column: "state", states: ["draft", "ready_for_review", "watermarked_delivered", "released"], actionGroup: "report_actions" },
  "subscriptions": { column: "state", states: ["trialing", "active", "past_due", "paused", "cancelled"], actionGroup: "subscription_actions" },
  "surveys": { column: "state", states: ["scheduled", "in_draft", "delivered", "cancelled"], actionGroup: "survey_actions" },
};
