/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_PricingGuide operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { PricingGuideListItem } from "@/openapi/litestarAPI.schemas";


export const pricingGuideColumnDefs = createColumnBuilder<PricingGuideListItem>()
  .text("name", { header: "Name", sortable: true })
  .boolean("is_active", { header: "Is Active", filterable: true })
  .datetime("created_at", { header: "Created", sortable: true, filterable: true, hideOnMobile: true })
  .build();

export const PricingGuideSortableColumn = {
  created_at: 'created_at',
  name: 'name',
} as const;

export const PricingGuideFilterableColumn = {
  created_at: 'created_at',
  is_active: 'is_active',
} as const;
