/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ListPaymentMethod400,
  ListRequest,
  PagedResponseAppDomainPaymentMethodsSchemasPaymentMethodListItem,
  PaymentMethodDetail,
  PaymentMethodsIdDetailHandler400
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary DetailHandler
 */
export const paymentMethodsIdDetailHandler = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaymentMethodDetail>(
      {url: `/payment-methods/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getPaymentMethodsIdDetailHandlerQueryKey = (id?: string,) => {
    return [
    `/payment-methods/${id}`
    ] as const;
    }

    
export const getPaymentMethodsIdDetailHandlerQueryOptions = <TData = Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError = PaymentMethodsIdDetailHandler400>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentMethodsIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>> = ({ signal }) => paymentMethodsIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentMethodsIdDetailHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>>
export type PaymentMethodsIdDetailHandlerQueryError = PaymentMethodsIdDetailHandler400


export function usePaymentMethodsIdDetailHandler<TData = Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError = PaymentMethodsIdDetailHandler400>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentMethodsIdDetailHandler<TData = Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError = PaymentMethodsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentMethodsIdDetailHandler<TData = Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError = PaymentMethodsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function usePaymentMethodsIdDetailHandler<TData = Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError = PaymentMethodsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentMethodsIdDetailHandlerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPaymentMethodsIdDetailHandlerSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError = PaymentMethodsIdDetailHandler400>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentMethodsIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>> = ({ signal }) => paymentMethodsIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentMethodsIdDetailHandlerSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>>
export type PaymentMethodsIdDetailHandlerSuspenseQueryError = PaymentMethodsIdDetailHandler400


export function usePaymentMethodsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError = PaymentMethodsIdDetailHandler400>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentMethodsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError = PaymentMethodsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentMethodsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError = PaymentMethodsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function usePaymentMethodsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError = PaymentMethodsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof paymentMethodsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentMethodsIdDetailHandlerSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ListHandler
 */
export const listPaymentMethod = (
    listRequest: ListRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PagedResponseAppDomainPaymentMethodsSchemasPaymentMethodListItem>(
      {url: `/payment-methods`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listRequest, signal
    },
      );
    }
  



export const getListPaymentMethodQueryKey = (listRequest?: ListRequest,) => {
    return [
    `/payment-methods`, listRequest
    ] as const;
    }

    
export const getListPaymentMethodQueryOptions = <TData = Awaited<ReturnType<typeof listPaymentMethod>>, TError = ListPaymentMethod400>(listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPaymentMethodQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPaymentMethod>>> = ({ signal }) => listPaymentMethod(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPaymentMethodQueryResult = NonNullable<Awaited<ReturnType<typeof listPaymentMethod>>>
export type ListPaymentMethodQueryError = ListPaymentMethod400


export function useListPaymentMethod<TData = Awaited<ReturnType<typeof listPaymentMethod>>, TError = ListPaymentMethod400>(
 listRequest: ListRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaymentMethod>>,
          TError,
          Awaited<ReturnType<typeof listPaymentMethod>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaymentMethod<TData = Awaited<ReturnType<typeof listPaymentMethod>>, TError = ListPaymentMethod400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPaymentMethod>>,
          TError,
          Awaited<ReturnType<typeof listPaymentMethod>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaymentMethod<TData = Awaited<ReturnType<typeof listPaymentMethod>>, TError = ListPaymentMethod400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListPaymentMethod<TData = Awaited<ReturnType<typeof listPaymentMethod>>, TError = ListPaymentMethod400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPaymentMethodQueryOptions(listRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getListPaymentMethodSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listPaymentMethod>>, TError = ListPaymentMethod400>(listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPaymentMethodQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPaymentMethod>>> = ({ signal }) => listPaymentMethod(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPaymentMethodSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listPaymentMethod>>>
export type ListPaymentMethodSuspenseQueryError = ListPaymentMethod400


export function useListPaymentMethodSuspense<TData = Awaited<ReturnType<typeof listPaymentMethod>>, TError = ListPaymentMethod400>(
 listRequest: ListRequest, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaymentMethodSuspense<TData = Awaited<ReturnType<typeof listPaymentMethod>>, TError = ListPaymentMethod400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPaymentMethodSuspense<TData = Awaited<ReturnType<typeof listPaymentMethod>>, TError = ListPaymentMethod400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListPaymentMethodSuspense<TData = Awaited<ReturnType<typeof listPaymentMethod>>, TError = ListPaymentMethod400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPaymentMethod>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPaymentMethodSuspenseQueryOptions(listRequest,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




