/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_Survey operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { SurveyListItem } from "@/openapi/litestarAPI.schemas";
import { SurveyState } from "@/openapi/litestarAPI.schemas";

export const surveyColumnDefs = createColumnBuilder<SurveyListItem>()
  .status("state", { header: "State", filterable: true, options: Object.values(SurveyState) })
  .entity("vessel", { header: "Vessel" })
  .entity("surveyor", { header: "Surveyor" })
  .datetime("created_at", { header: "Created", sortable: true, filterable: true, hideOnMobile: true })
  .build();

export const SurveySortableColumn = {
  created_at: 'created_at',
} as const;

export const SurveyFilterableColumn = {
  assigned_surveyor_id: 'assigned_surveyor_id',
  created_at: 'created_at',
  state: 'state',
  vessel_id: 'vessel_id',
} as const;
