/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_EmailThread operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { ThreadListItem } from "@/openapi/litestarAPI.schemas";
import { MessageDirection } from "@/openapi/litestarAPI.schemas";

export const emailThreadColumnDefs = createColumnBuilder<ThreadListItem>()
  .text("subject", { header: "Subject" })
  .text("latest_from", { header: "Latest From" })
  .text("latest_snippet", { header: "Latest Snippet" })
  .datetime("latest_activity_at", { header: "Latest Activity", hideOnMobile: true })
  .enum("latest_direction", { header: "Latest Direction", options: Object.values(MessageDirection) })
  .number("unread_count", { header: "Unread Count" })
  .datetime("archived_at", { header: "Archived", filterable: true, hideOnMobile: true })
  .build();

export const EmailThreadSortableColumn = {
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const;

export const EmailThreadFilterableColumn = {
  archived_at: 'archived_at',
  client_id: 'client_id',
  has_outbound: 'has_outbound',
  has_unread_inbound: 'has_unread_inbound',
  survey_id: 'survey_id',
} as const;
