/**
 * Generated by generate-forms.ts — DO NOT EDIT
 */
import type { ReactElement } from "react";
import {
  ClientActionsCreateForm,
  ClientActionsUpdateForm,
  VesselActionsCreateForm,
  VesselActionsUpdateForm,
  EngineActionsCreateForm,
  EngineActionsUpdateForm,
  EmailThreadActionsComposeForm,
  MessageActionsReplyToThreadForm,
  MessageActionsForwardMessageForm,
  InvoiceActionsCreateForm,
  InvoiceActionsUpdateForm,
  InvoiceLineItemActionsCreateForm,
  InvoiceLineItemActionsUpdateForm,
  SubscriptionActionsCreateForm,
  SubscriptionActionsUpdateForm,
  PricingGuideActionsCreateForm,
  PricingGuideActionsUpdateForm,
  PricingTierActionsCreateForm,
  PricingTierActionsUpdateForm,
  CalendarEventActionsCreateForm,
  CalendarEventActionsUpdateForm,
  ManufacturerActionsCreateForm,
  ManufacturerActionsUpdateForm,
  PartActionsCreateForm,
  PartActionsUpdateForm,
  SurveyActionsCreateForm,
  SurveyActionsUpdateForm,
  SurveyTemplateActionsCreateForm,
  SurveyTemplateActionsUpdateForm,
  SurveyMediaActionsSetCaptionForm,
  OnboardingActionsClaimInboxForm,
  OnboardingActionsConfirmPricingForm,
  ReportActionsCreateForm,
  ReportActionsUpdateForm,
  WidgetActionsCreateForm,
  WidgetActionsUpdateForm,
} from "./forms.gen";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const generatedRegistry: Record<string, { render: (params: any) => ReactElement }> = {
  "client_actions__create": {
    render: (params) => <ClientActionsCreateForm {...params} />,
  },
  "client_actions__update": {
    render: (params) => <ClientActionsUpdateForm {...params} />,
  },
  "vessel_actions__create": {
    render: (params) => <VesselActionsCreateForm {...params} />,
  },
  "vessel_actions__update": {
    render: (params) => <VesselActionsUpdateForm {...params} />,
  },
  "engine_actions__create": {
    render: (params) => <EngineActionsCreateForm {...params} />,
  },
  "engine_actions__update": {
    render: (params) => <EngineActionsUpdateForm {...params} />,
  },
  "email_thread_actions__compose": {
    render: (params) => <EmailThreadActionsComposeForm {...params} />,
  },
  "message_actions__reply_to_thread": {
    render: (params) => <MessageActionsReplyToThreadForm {...params} />,
  },
  "message_actions__forward_message": {
    render: (params) => <MessageActionsForwardMessageForm {...params} />,
  },
  "invoice_actions__create": {
    render: (params) => <InvoiceActionsCreateForm {...params} />,
  },
  "invoice_actions__update": {
    render: (params) => <InvoiceActionsUpdateForm {...params} />,
  },
  "invoice_line_item_actions__create": {
    render: (params) => <InvoiceLineItemActionsCreateForm {...params} />,
  },
  "invoice_line_item_actions__update": {
    render: (params) => <InvoiceLineItemActionsUpdateForm {...params} />,
  },
  "subscription_actions__create": {
    render: (params) => <SubscriptionActionsCreateForm {...params} />,
  },
  "subscription_actions__update": {
    render: (params) => <SubscriptionActionsUpdateForm {...params} />,
  },
  "pricing_guide_actions__create": {
    render: (params) => <PricingGuideActionsCreateForm {...params} />,
  },
  "pricing_guide_actions__update": {
    render: (params) => <PricingGuideActionsUpdateForm {...params} />,
  },
  "pricing_tier_actions__create": {
    render: (params) => <PricingTierActionsCreateForm {...params} />,
  },
  "pricing_tier_actions__update": {
    render: (params) => <PricingTierActionsUpdateForm {...params} />,
  },
  "calendar_event_actions__create": {
    render: (params) => <CalendarEventActionsCreateForm {...params} />,
  },
  "calendar_event_actions__update": {
    render: (params) => <CalendarEventActionsUpdateForm {...params} />,
  },
  "manufacturer_actions__create": {
    render: (params) => <ManufacturerActionsCreateForm {...params} />,
  },
  "manufacturer_actions__update": {
    render: (params) => <ManufacturerActionsUpdateForm {...params} />,
  },
  "part_actions__create": {
    render: (params) => <PartActionsCreateForm {...params} />,
  },
  "part_actions__update": {
    render: (params) => <PartActionsUpdateForm {...params} />,
  },
  "survey_actions__create": {
    render: (params) => <SurveyActionsCreateForm {...params} />,
  },
  "survey_actions__update": {
    render: (params) => <SurveyActionsUpdateForm {...params} />,
  },
  "survey_template_actions__create": {
    render: (params) => <SurveyTemplateActionsCreateForm {...params} />,
  },
  "survey_template_actions__update": {
    render: (params) => <SurveyTemplateActionsUpdateForm {...params} />,
  },
  "survey_media_actions__set_caption": {
    render: (params) => <SurveyMediaActionsSetCaptionForm {...params} />,
  },
  "onboarding_actions__claim_inbox": {
    render: (params) => <OnboardingActionsClaimInboxForm {...params} />,
  },
  "onboarding_actions__confirm_pricing": {
    render: (params) => <OnboardingActionsConfirmPricingForm {...params} />,
  },
  "report_actions__create": {
    render: (params) => <ReportActionsCreateForm {...params} />,
  },
  "report_actions__update": {
    render: (params) => <ReportActionsUpdateForm {...params} />,
  },
  "widget_actions__create": {
    render: (params) => <WidgetActionsCreateForm {...params} />,
  },
  "widget_actions__update": {
    render: (params) => <WidgetActionsUpdateForm {...params} />,
  },
};
