/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DocumentResponseSchema,
  DocumentSchema,
  DocumentsIdDeleteDocument200,
  DocumentsIdDeleteDocument400,
  DocumentsIdGetDocument400,
  DocumentsPresignedUploadRequestPresignedUpload400,
  DocumentsRegisterRegisterDocument400,
  DocumentsSchemasPresignedUploadRequestSchema,
  DocumentsSchemasPresignedUploadResponseSchema,
  RegisterDocumentSchema
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary RequestPresignedUpload
 */
export const documentsPresignedUploadRequestPresignedUpload = (
    documentsSchemasPresignedUploadRequestSchema: DocumentsSchemasPresignedUploadRequestSchema,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentsSchemasPresignedUploadResponseSchema>(
      {url: `/documents/presigned-upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: documentsSchemasPresignedUploadRequestSchema, signal
    },
      );
    }
  


export const getDocumentsPresignedUploadRequestPresignedUploadMutationOptions = <TError = DocumentsPresignedUploadRequestPresignedUpload400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof documentsPresignedUploadRequestPresignedUpload>>, TError,{data: DocumentsSchemasPresignedUploadRequestSchema}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof documentsPresignedUploadRequestPresignedUpload>>, TError,{data: DocumentsSchemasPresignedUploadRequestSchema}, TContext> => {

const mutationKey = ['documentsPresignedUploadRequestPresignedUpload'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof documentsPresignedUploadRequestPresignedUpload>>, {data: DocumentsSchemasPresignedUploadRequestSchema}> = (props) => {
          const {data} = props ?? {};

          return  documentsPresignedUploadRequestPresignedUpload(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DocumentsPresignedUploadRequestPresignedUploadMutationResult = NonNullable<Awaited<ReturnType<typeof documentsPresignedUploadRequestPresignedUpload>>>
    export type DocumentsPresignedUploadRequestPresignedUploadMutationBody = DocumentsSchemasPresignedUploadRequestSchema
    export type DocumentsPresignedUploadRequestPresignedUploadMutationError = DocumentsPresignedUploadRequestPresignedUpload400

    /**
 * @summary RequestPresignedUpload
 */
export const useDocumentsPresignedUploadRequestPresignedUpload = <TError = DocumentsPresignedUploadRequestPresignedUpload400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof documentsPresignedUploadRequestPresignedUpload>>, TError,{data: DocumentsSchemasPresignedUploadRequestSchema}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof documentsPresignedUploadRequestPresignedUpload>>,
        TError,
        {data: DocumentsSchemasPresignedUploadRequestSchema},
        TContext
      > => {

      const mutationOptions = getDocumentsPresignedUploadRequestPresignedUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary RegisterDocument
 */
export const documentsRegisterRegisterDocument = (
    registerDocumentSchema: RegisterDocumentSchema,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentSchema>(
      {url: `/documents/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDocumentSchema, signal
    },
      );
    }
  


export const getDocumentsRegisterRegisterDocumentMutationOptions = <TError = DocumentsRegisterRegisterDocument400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof documentsRegisterRegisterDocument>>, TError,{data: RegisterDocumentSchema}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof documentsRegisterRegisterDocument>>, TError,{data: RegisterDocumentSchema}, TContext> => {

const mutationKey = ['documentsRegisterRegisterDocument'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof documentsRegisterRegisterDocument>>, {data: RegisterDocumentSchema}> = (props) => {
          const {data} = props ?? {};

          return  documentsRegisterRegisterDocument(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DocumentsRegisterRegisterDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof documentsRegisterRegisterDocument>>>
    export type DocumentsRegisterRegisterDocumentMutationBody = RegisterDocumentSchema
    export type DocumentsRegisterRegisterDocumentMutationError = DocumentsRegisterRegisterDocument400

    /**
 * @summary RegisterDocument
 */
export const useDocumentsRegisterRegisterDocument = <TError = DocumentsRegisterRegisterDocument400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof documentsRegisterRegisterDocument>>, TError,{data: RegisterDocumentSchema}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof documentsRegisterRegisterDocument>>,
        TError,
        {data: RegisterDocumentSchema},
        TContext
      > => {

      const mutationOptions = getDocumentsRegisterRegisterDocumentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary GetDocument
 */
export const documentsIdGetDocument = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentResponseSchema>(
      {url: `/documents/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getDocumentsIdGetDocumentQueryKey = (id?: string,) => {
    return [
    `/documents/${id}`
    ] as const;
    }

    
export const getDocumentsIdGetDocumentQueryOptions = <TData = Awaited<ReturnType<typeof documentsIdGetDocument>>, TError = DocumentsIdGetDocument400>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDocumentsIdGetDocumentQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof documentsIdGetDocument>>> = ({ signal }) => documentsIdGetDocument(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DocumentsIdGetDocumentQueryResult = NonNullable<Awaited<ReturnType<typeof documentsIdGetDocument>>>
export type DocumentsIdGetDocumentQueryError = DocumentsIdGetDocument400


export function useDocumentsIdGetDocument<TData = Awaited<ReturnType<typeof documentsIdGetDocument>>, TError = DocumentsIdGetDocument400>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof documentsIdGetDocument>>,
          TError,
          Awaited<ReturnType<typeof documentsIdGetDocument>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDocumentsIdGetDocument<TData = Awaited<ReturnType<typeof documentsIdGetDocument>>, TError = DocumentsIdGetDocument400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof documentsIdGetDocument>>,
          TError,
          Awaited<ReturnType<typeof documentsIdGetDocument>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDocumentsIdGetDocument<TData = Awaited<ReturnType<typeof documentsIdGetDocument>>, TError = DocumentsIdGetDocument400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetDocument
 */

export function useDocumentsIdGetDocument<TData = Awaited<ReturnType<typeof documentsIdGetDocument>>, TError = DocumentsIdGetDocument400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDocumentsIdGetDocumentQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getDocumentsIdGetDocumentSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof documentsIdGetDocument>>, TError = DocumentsIdGetDocument400>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDocumentsIdGetDocumentQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof documentsIdGetDocument>>> = ({ signal }) => documentsIdGetDocument(id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DocumentsIdGetDocumentSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof documentsIdGetDocument>>>
export type DocumentsIdGetDocumentSuspenseQueryError = DocumentsIdGetDocument400


export function useDocumentsIdGetDocumentSuspense<TData = Awaited<ReturnType<typeof documentsIdGetDocument>>, TError = DocumentsIdGetDocument400>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDocumentsIdGetDocumentSuspense<TData = Awaited<ReturnType<typeof documentsIdGetDocument>>, TError = DocumentsIdGetDocument400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDocumentsIdGetDocumentSuspense<TData = Awaited<ReturnType<typeof documentsIdGetDocument>>, TError = DocumentsIdGetDocument400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetDocument
 */

export function useDocumentsIdGetDocumentSuspense<TData = Awaited<ReturnType<typeof documentsIdGetDocument>>, TError = DocumentsIdGetDocument400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsIdGetDocument>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDocumentsIdGetDocumentSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary DeleteDocument
 */
export const documentsIdDeleteDocument = (
    id: string,
 ) => {
      
      
      return customInstance<DocumentsIdDeleteDocument200>(
      {url: `/documents/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDocumentsIdDeleteDocumentMutationOptions = <TError = DocumentsIdDeleteDocument400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof documentsIdDeleteDocument>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof documentsIdDeleteDocument>>, TError,{id: string}, TContext> => {

const mutationKey = ['documentsIdDeleteDocument'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof documentsIdDeleteDocument>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  documentsIdDeleteDocument(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DocumentsIdDeleteDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof documentsIdDeleteDocument>>>
    
    export type DocumentsIdDeleteDocumentMutationError = DocumentsIdDeleteDocument400

    /**
 * @summary DeleteDocument
 */
export const useDocumentsIdDeleteDocument = <TError = DocumentsIdDeleteDocument400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof documentsIdDeleteDocument>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof documentsIdDeleteDocument>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDocumentsIdDeleteDocumentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary ListDocuments
 */
export const documentsListDocuments = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentResponseSchema[]>(
      {url: `/documents`, method: 'GET', signal
    },
      );
    }
  



export const getDocumentsListDocumentsQueryKey = () => {
    return [
    `/documents`
    ] as const;
    }

    
export const getDocumentsListDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof documentsListDocuments>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDocumentsListDocumentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof documentsListDocuments>>> = ({ signal }) => documentsListDocuments(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DocumentsListDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof documentsListDocuments>>>
export type DocumentsListDocumentsQueryError = unknown


export function useDocumentsListDocuments<TData = Awaited<ReturnType<typeof documentsListDocuments>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof documentsListDocuments>>,
          TError,
          Awaited<ReturnType<typeof documentsListDocuments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDocumentsListDocuments<TData = Awaited<ReturnType<typeof documentsListDocuments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof documentsListDocuments>>,
          TError,
          Awaited<ReturnType<typeof documentsListDocuments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDocumentsListDocuments<TData = Awaited<ReturnType<typeof documentsListDocuments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListDocuments
 */

export function useDocumentsListDocuments<TData = Awaited<ReturnType<typeof documentsListDocuments>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDocumentsListDocumentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getDocumentsListDocumentsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof documentsListDocuments>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDocumentsListDocumentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof documentsListDocuments>>> = ({ signal }) => documentsListDocuments(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DocumentsListDocumentsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof documentsListDocuments>>>
export type DocumentsListDocumentsSuspenseQueryError = unknown


export function useDocumentsListDocumentsSuspense<TData = Awaited<ReturnType<typeof documentsListDocuments>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDocumentsListDocumentsSuspense<TData = Awaited<ReturnType<typeof documentsListDocuments>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDocumentsListDocumentsSuspense<TData = Awaited<ReturnType<typeof documentsListDocuments>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListDocuments
 */

export function useDocumentsListDocumentsSuspense<TData = Awaited<ReturnType<typeof documentsListDocuments>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof documentsListDocuments>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDocumentsListDocumentsSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




