/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  SearchResponse,
  SearchSearch400,
  SearchSearchParams
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary Search
 */
export const searchSearch = (
    params?: SearchSearchParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SearchResponse>(
      {url: `/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchSearchQueryKey = (params?: SearchSearchParams,) => {
    return [
    `/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchSearchQueryOptions = <TData = Awaited<ReturnType<typeof searchSearch>>, TError = SearchSearch400>(params?: SearchSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchSearch>>> = ({ signal }) => searchSearch(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchSearchQueryResult = NonNullable<Awaited<ReturnType<typeof searchSearch>>>
export type SearchSearchQueryError = SearchSearch400


export function useSearchSearch<TData = Awaited<ReturnType<typeof searchSearch>>, TError = SearchSearch400>(
 params: undefined |  SearchSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchSearch>>,
          TError,
          Awaited<ReturnType<typeof searchSearch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchSearch<TData = Awaited<ReturnType<typeof searchSearch>>, TError = SearchSearch400>(
 params?: SearchSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchSearch>>,
          TError,
          Awaited<ReturnType<typeof searchSearch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchSearch<TData = Awaited<ReturnType<typeof searchSearch>>, TError = SearchSearch400>(
 params?: SearchSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search
 */

export function useSearchSearch<TData = Awaited<ReturnType<typeof searchSearch>>, TError = SearchSearch400>(
 params?: SearchSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getSearchSearchSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof searchSearch>>, TError = SearchSearch400>(params?: SearchSearchParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchSearch>>> = ({ signal }) => searchSearch(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchSearchSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof searchSearch>>>
export type SearchSearchSuspenseQueryError = SearchSearch400


export function useSearchSearchSuspense<TData = Awaited<ReturnType<typeof searchSearch>>, TError = SearchSearch400>(
 params: undefined |  SearchSearchParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchSearchSuspense<TData = Awaited<ReturnType<typeof searchSearch>>, TError = SearchSearch400>(
 params?: SearchSearchParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchSearchSuspense<TData = Awaited<ReturnType<typeof searchSearch>>, TError = SearchSearch400>(
 params?: SearchSearchParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search
 */

export function useSearchSearchSuspense<TData = Awaited<ReturnType<typeof searchSearch>>, TError = SearchSearch400>(
 params?: SearchSearchParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchSearch>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchSearchSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




