/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_Part operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { PartListItem } from "@/openapi/litestarAPI.schemas";
import { PartCategory } from "@/openapi/litestarAPI.schemas";

export const partColumnDefs = createColumnBuilder<PartListItem>()
  .text("name", { header: "Name", sortable: true, filterable: true })
  .text("part_number", { header: "Part Number" })
  .enum("category", { header: "Category", sortable: true, filterable: true, options: Object.values(PartCategory) })
  .datetime("created_at", { header: "Created", sortable: true, filterable: true, hideOnMobile: true })
  .build();

export const PartSortableColumn = {
  category: 'category',
  created_at: 'created_at',
  name: 'name',
} as const;

export const PartFilterableColumn = {
  category: 'category',
  created_at: 'created_at',
  manufacturer_id: 'manufacturer_id',
  name: 'name',
} as const;
