/**
 * Generated by generate-columns.ts — DO NOT EDIT
 * Source: list_Report operation
 */
import { createColumnBuilder } from "@/lib/column-builder";
import type { ReportListItem } from "@/openapi/litestarAPI.schemas";
import { ReportState } from "@/openapi/litestarAPI.schemas";

export const reportColumnDefs = createColumnBuilder<ReportListItem>()
  .status("state", { header: "State", filterable: true, options: Object.values(ReportState) })
  .text("title", { header: "Title", sortable: true })
  .datetime("created_at", { header: "Created", sortable: true, filterable: true, hideOnMobile: true })
  .build();

export const ReportSortableColumn = {
  created_at: 'created_at',
  title: 'title',
} as const;

export const ReportFilterableColumn = {
  created_at: 'created_at',
  state: 'state',
  survey_id: 'survey_id',
} as const;
