/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ListReport400,
  ListRequest,
  PagedResponseAppDomainReportsSchemasReportListItem,
  ReportDetail,
  ReportsIdDetailHandler400
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary DetailHandler
 */
export const reportsIdDetailHandler = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ReportDetail>(
      {url: `/reports/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getReportsIdDetailHandlerQueryKey = (id?: string,) => {
    return [
    `/reports/${id}`
    ] as const;
    }

    
export const getReportsIdDetailHandlerQueryOptions = <TData = Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError = ReportsIdDetailHandler400>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsIdDetailHandler>>> = ({ signal }) => reportsIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsIdDetailHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof reportsIdDetailHandler>>>
export type ReportsIdDetailHandlerQueryError = ReportsIdDetailHandler400


export function useReportsIdDetailHandler<TData = Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError = ReportsIdDetailHandler400>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof reportsIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsIdDetailHandler<TData = Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError = ReportsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsIdDetailHandler>>,
          TError,
          Awaited<ReturnType<typeof reportsIdDetailHandler>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsIdDetailHandler<TData = Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError = ReportsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useReportsIdDetailHandler<TData = Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError = ReportsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsIdDetailHandlerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getReportsIdDetailHandlerSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError = ReportsIdDetailHandler400>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsIdDetailHandlerQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsIdDetailHandler>>> = ({ signal }) => reportsIdDetailHandler(id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsIdDetailHandlerSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof reportsIdDetailHandler>>>
export type ReportsIdDetailHandlerSuspenseQueryError = ReportsIdDetailHandler400


export function useReportsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError = ReportsIdDetailHandler400>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError = ReportsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError = ReportsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary DetailHandler
 */

export function useReportsIdDetailHandlerSuspense<TData = Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError = ReportsIdDetailHandler400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof reportsIdDetailHandler>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsIdDetailHandlerSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ListHandler
 */
export const listReport = (
    listRequest: ListRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PagedResponseAppDomainReportsSchemasReportListItem>(
      {url: `/reports`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listRequest, signal
    },
      );
    }
  



export const getListReportQueryKey = (listRequest?: ListRequest,) => {
    return [
    `/reports`, listRequest
    ] as const;
    }

    
export const getListReportQueryOptions = <TData = Awaited<ReturnType<typeof listReport>>, TError = ListReport400>(listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListReportQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listReport>>> = ({ signal }) => listReport(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListReportQueryResult = NonNullable<Awaited<ReturnType<typeof listReport>>>
export type ListReportQueryError = ListReport400


export function useListReport<TData = Awaited<ReturnType<typeof listReport>>, TError = ListReport400>(
 listRequest: ListRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReport>>,
          TError,
          Awaited<ReturnType<typeof listReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReport<TData = Awaited<ReturnType<typeof listReport>>, TError = ListReport400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReport>>,
          TError,
          Awaited<ReturnType<typeof listReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReport<TData = Awaited<ReturnType<typeof listReport>>, TError = ListReport400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListReport<TData = Awaited<ReturnType<typeof listReport>>, TError = ListReport400>(
 listRequest: ListRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListReportQueryOptions(listRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getListReportSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listReport>>, TError = ListReport400>(listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListReportQueryKey(listRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listReport>>> = ({ signal }) => listReport(listRequest, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListReportSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listReport>>>
export type ListReportSuspenseQueryError = ListReport400


export function useListReportSuspense<TData = Awaited<ReturnType<typeof listReport>>, TError = ListReport400>(
 listRequest: ListRequest, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReportSuspense<TData = Awaited<ReturnType<typeof listReport>>, TError = ListReport400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReportSuspense<TData = Awaited<ReturnType<typeof listReport>>, TError = ListReport400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListHandler
 */

export function useListReportSuspense<TData = Awaited<ReturnType<typeof listReport>>, TError = ListReport400>(
 listRequest: ListRequest, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListReportSuspenseQueryOptions(listRequest,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




